### ISSUE TITLE
Seemingly wrong ClinVar annotation for chr17:7676154:G->C

### ISSUE THREAD

**Issue by BoPeng** [KarchinLab/open-cravat#101]
I was curious what exactly does "drug response" mean for the annotation of Chr17:7676154:C->G so I checked the record of [12351 of clinvar](https://www.ncbi.nlm.nih.gov/clinvar/variation/12351/?new_evidence=false). The page does not show any drug for current and previous annotations so I am wondering why "drug response" was returned for this variant. 

<img width="1833" alt="image" src="https://user-images.githubusercontent.com/9889312/157096753-75bcf068-8786-42e2-803c-b5773b30929f.png">

**Comment by rkimoakbioinformatics** [comment]
@BoPeng Thanks for letting us know. Indeed it was a bug. I have just updated `clinvar` with the newest 2022/03/06 data and the issue does not exist in it. Please update the clinvar module (with `oc module update clinvar` or through the OpenCRAVAT GUI) to version 2022.03.06 and try that one.

**Comment by BoPeng** [comment]
Thanks. I can confirm that the issue has been resolved.
