### ISSUE TITLE
PyVCF error

### ISSUE THREAD

**Issue by DCGenomics** [KarchinLab/open-cravat#115]
Hi folks, I've seen this error on a number of systems.  

Any help would be greatly appreciated!

Collecting pyvcf
  Downloading PyVCF-0.6.8.tar.gz (34 kB)
  Preparing metadata (setup.py): started
  Preparing metadata (setup.py): finished with status 'error'

  error: subprocess-exited-with-error
  
  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [1 lines of output]
      error in PyVCF setup command: use_2to3 is invalid.
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.

**Comment by kmoad** [comment]
Looks like this issue is in PyVCF at https://github.com/jamescasbon/PyVCF/issues/334, but the project isn't maintained. So PyVCF has been forked into https://github.com/dridk/PyVCF3, now called pyvcf3, .

There are a few other changes in pyvcf3. We'll look into switching to the fork. It may take a bit to test it.

**Comment by mryaninsilico** [comment]
Looks like this type of error has been seen by others.  When you see this, could you try installing an older version of setuptools and see if this suggestion is correct.  setuptools<58  https://stackoverflow.com/questions/69100275/error-while-downloading-the-requirements-using-pip-install-setup-command-use-2.

 

  

 

From: Ben Busby ***@***.***> 
Sent: Thursday, June 9, 2022 11:42 AM
To: KarchinLab/open-cravat ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [KarchinLab/open-cravat] PyVCF error (Issue #115)

 

Hi folks, I've seen this error on a number of systems.

Any help would be greatly appreciated!

Collecting pyvcf
Downloading PyVCF-0.6.8.tar.gz (34 kB)
Preparing metadata (setup.py): started
Preparing metadata (setup.py): finished with status 'error'

error: subprocess-exited-with-error

× python setup.py egg_info did not run successfully.
│ exit code: 1
╰─> [1 lines of output]
error in PyVCF setup command: use_2to3 is invalid.
[end of output]

note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.

**Comment by kmoad** [comment]
I've tested PyVCF3 against a number of VCFs from different sources. Haven't seen any regressions. Next oc release replaces pyvcf with PyVCF3.
