### ISSUE TITLE
Python API issue

### ISSUE THREAD

**Issue by haochenz96** [KarchinLab/open-cravat#118]
Hi Rick,

I have been running lots of samples through the Python API and it has been working quite well. Thanks again for providing this amazing tool.

I recently ran into 2 issues while submitting jobs through the Python API:

1. sometimes the output I get (with `response = session.get(
        'https://run.opencravat.org/submit/jobs/' + job_id + '/status')`) contains different numbers of variants than what I put in. I have been searching around on my end but could not locate any bug. What could be the cause of this?

2. My very recent jobs all show as `"submitted"` status without any response after a long time. When I attempt to click to see the log it says the log file does not exist.

Let me know what you think of these! Happy to DM any information you need if more convenient.

Best,
Haochen

**Comment by mryaninsilico** [comment]
Hi Haochen,

 

Thanks for reporting the issue.  We will take a look at the issue with python API submission and number of variants returned.

 

The run.opencravat.org server was restarted this morning to correct the issue with submitted jobs not getting processed.  You may need to resubmit the jobs that did not run.

 

Michael Ryan, PhD

Kiromic

 

From: Haochen Zhang ***@***.***> 
Sent: Monday, July 11, 2022 12:43 AM
To: KarchinLab/open-cravat ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [KarchinLab/open-cravat] Python API issue (Issue #118)

 

Hi Rick,

I have been running lots of samples through the Python API and it has been working quite well. Thanks again for providing this amazing tool.

I recently ran into 2 issues while submitting jobs through the Python API:

1.	sometimes the output I get (with response = session.get( 'https://run.opencravat.org/submit/jobs/' + job_id + '/status')) contains different numbers of variants than what I put in. I have been searching around on my end but could not locate any bug. What could be the cause of this?
2.	My very recent jobs all show as "submitted" status without any response after a long time. When I attempt to click to see the log it says the log file does not exist.

Let me know what you think of these! Happy to DM any information you need if more convenient.

Best,
Haochen

**Comment by haochenz96** [comment]
Thank you Michael! 

Just to give you more information regarding the difference between input & output issue: I tried to rerun the job a couple of times and it worked, so I assumed it is not specific to my input variant list.

For future reference, will an issue like server restart be posted somewhere to notify users?

**Comment by kmoad** [comment]
For a multi-allelic vcf, the `num_unique_var` key in the status response is the number of variants that oc finds. The `num_input_var` key is not reliable for files that can contain more than one variant per line. We'll probably deprecate it in the future.

We schedule server restarts for when no jobs are being processed. Restarts don't take long, so it's there's usually a window. In the rare case we need to restart while a job is running, we resubmit jobs once the server is up.
