### ISSUE TITLE
can't read vcf Strelka2 formated 

### ISSUE THREAD

**Issue by lmanchon** [KarchinLab/open-cravat#120]
--Hi,

open-cravat failed when vcf input file is generated with Strelka2.
Why ?
see input vcf file in attachement
[somatic.snvs.vcf.zip](https://github.com/KarchinLab/open-cravat/files/9268526/somatic.snvs.vcf.zip)

**Comment by kmoad** [comment]
Hi Imanchon. Thanks for the report. Especially thanks for attaching the vcf that caused the issue.

It looks like vcfs from Strelka2 don't have the `GT` field that oc uses to call whether or not a sample has the variant. This surprised me, as most other variant callers use it. I'm doing some reading to understand how Strelka formats their vcfs. Mostly this issue,

https://github.com/Illumina/strelka/issues/16

If you know anything more about how to parse Strelka vcfs, I'd be happy to hear it.

**Comment by kmoad** [comment]
Just put out vcf-converter 2.1.5 with a fix.

Variants in VCFs without the GT field will be annotated, but zygosity for all samples will be blank.

It's available for download, and up at [run.opencravat.org](https://run.opencravat.org).

Here's the commit:
https://github.com/KarchinLab/open-cravat-modules-karchinlab/commit/127ae76eadc686d376f49743f73b0edb81e6d3c5
