### ISSUE TITLE
ensembl exon number

### ISSUE THREAD

**Issue by cheanney** [KarchinLab/open-cravat#125]
Hi Team, 

Is there any chance to provide ensembl exon number as one of the annotations?

Thanks,

Anney

**Comment by kmoad** [comment]
Sorry for the delayed response. This has been added to our queue.

**Comment by kmoad** [comment]
This has been added in oc version 2.4.1 and mapper version 1.1.0.

https://github.com/KarchinLab/open-cravat/commit/da98183d4f3986b0a257fa8eed6cdcb13888f536
https://github.com/KarchinLab/open-cravat-modules-karchinlab/commit/97f3ceddcd8956709cbb39350ae8bb46260da47b
