### ISSUE TITLE
GQ and gnomad3_counts annotator module

### ISSUE THREAD

**Issue by PabloRomanjo** [KarchinLab/open-cravat#126]
Dear Cravat team,

First of all, thank you very much for this fantastic tool, I am using it a lot.

I have two questions/doubts/suggestions:

1. **Is it possible to annotate the GQ value from vcfinfo?** I found that we can annotate AC (extra_vcf_info__AC), DP (extra_vcf_info__DP), MQ, QD, MLEAF, ExcessHet ... (and others) but not GQ.

2. The second is related to the **gnomad3_counts annotator module**. I have been investigating on it, and I think that it is only possible to annotate the count of homozygotes for a certain position (for example, using gnomad3_counts__nfe). I do not know exactly the utility of this, but I think it could be easily improved if, instead of (or in a complementary way to) the count of homozygous, this annotator would return the total **alt_allele count** (count of alt homozygous * 2 + count of heterozygous) and **ref_allele count**  ref_allele count (ref homozygous * 2 + count of heterozygous) for the variant position. These numbers would allow to perform further analysis. 
 
Again, thank you very much for your efforts.

Pablo Román-Naranjo Varela
Otology & Neurotology Group CTS495
Genomic Medicine Area
Centro Pfizer - Universidad de Granada - Junta de Andalucía de Genómica e Investigación Oncológica (GENYO)
Granada | Spain

**Comment by mlarsen2** [comment]
It's great to hear that you are enjoying OpenCRAVAT!

In response to your question about the GQ value, in the Extra VCF INFO Annotations section there should be 2 fields for "GQ_mean" and "GQ_STDDEV". If you do not see them there, feel free to send us your input file and we can see what's going on.

The gnomad3_counts annotator does only count the homozygotes, and your suggestion of the total alt and total ref counts would be a great addition. We will update you when the new counts have been implemented into OpenCRAVAT!
