### ISSUE TITLE
Result viewer problems

### ISSUE THREAD

**Issue by janetj1968** [KarchinLab/open-cravat#127]
Hi- I am using the Windows version.

My Open Cravat had been working (jobs ran and stored successfully), but now when I go into the result viewer, the table no longer displays.  Basically everything looks blank besides the logo, layout tab and on the right, the fields view table, ?, email and save to disc icons.

I have trying uninstalling and reinstalling, but no change.

Thanks for your help.

**Comment by kmoad** [comment]
Hi, thanks for the report. A few questions to help us track this down.

1) What version of oc are you using? Version number is in the top right of the submit page.
2) Where is the job database? In the submit page, click on the row for the job you want. It will open job details. What is the "Job Directory".
3) When you open the job are there any errors in the browser console? Open the job, then press the ctrl-shift-j. There will be some text that shows up. We're interested in what anything in red says.

**Comment by janetj1968** [comment]
Thank you for taking the time to write!
I am using version 2.2.7

The job database is in e:\jobs

There don't appear to be any errors, but its possibly looking like that
isn't loading correctly either.  I am attaching screenshots.

It just popped up that there is an update available.  Should I just try
that to see if it goes away?
Jan

**Comment by janetj1968** [comment]
To me, its almost looking like the reporting structure (wherever its saved)
isn't calling or that its corrupted.  But it doesnt appear that
re-installing is looking to make sure that it re-writes it.

Thanks again for your help.

**Comment by janetj1968** [comment]
I just wanted to let you know that your latest update fixed the issue...its
working again!
I appreciate you so much!
Jan
