### ISSUE TITLE
add values in 'Total reads' column

### ISSUE THREAD

**Issue by lmanchon** [KarchinLab/open-cravat#129]
--Hi,
is there a parameter to change to add all the Total reads per sample even if the sample does not contain the mutation ?
For example i submitted 5 samples and in Total reads column i have only one value and not five.
thank you--

**Comment by kmoad** [comment]
Unfortunately, we don't have that parameter. OpenCRAVAT doesn't report total reads for samples with the reference allele. We'll consider changing this in future releases.
