### ISSUE TITLE
bug in "gnomad AD3 counts" module

### ISSUE THREAD

**Issue by EugeneEA** [KarchinLab/open-cravat#132]
Hi, there is a bug in "gnomad AD3 counts" module - column `Global homozygous Male AC` actually contains the sum for male and female, and the value in column `Global homozygous AC` also become 1.5x larger then in reality. See for example:
![image](https://user-images.githubusercontent.com/57629300/208647275-02ba9f55-e5be-4267-ae1c-46d47194bc1a.png)

and corresponding data from gnomadV3 web site:
![image](https://user-images.githubusercontent.com/57629300/208647405-00bf9dde-ec73-4ed2-9cd8-9fed0c6f9331.png)

**Comment by mlarsen2** [comment]
Thank you for bringing this to our attention this bug has been fixed in version 1.1.0 of the gnomad3_counts module.
