### ISSUE TITLE
Querry builder fails to detect data in filed [Variant annotation][Note]

### ISSUE THREAD

**Issue by EugeneEA** [KarchinLab/open-cravat#139]
Hi, 

I've noticed that "Querry builder" fails to apply any filters to Note column.
It does return zero variants when I'm trying to get SNPs with non-empty Note field even though I've put some info there.

Best, Eugene

**Comment by kmoad** [comment]
Thanks for the catch. We'll get it fixed and let you know.

**Comment by kmoad** [comment]
It is possible to filter on notes in version 2.3.1. Unfortunately, it is only possible on old jobs. There are two new columns, `variant_note` and `gene_note`. Both can be filtered on.

If you need to convert an old job, I can send you a script.

https://github.com/KarchinLab/open-cravat/commit/9ca2a68636b2c3f11cb884027dd6696bc9cd0e2d
