### ISSUE TITLE
Cannot find port

### ISSUE THREAD

**Issue by DSLituiev** [KarchinLab/open-cravat#14]
Hi
I am running your tool on a server, and I cannot figure out which port it is using? 
Please advise

**Comment by DSLituiev** [comment]
Also, is there a way to specify the port? I could not find it in docs

**Comment by rkiminsilico** [comment]
Hi, the default port used by `wcravat` is 8060. The next release which will come soon will print out which port it is using on the terminal. Also, when you run `wcravat`, it automatically opens the system's default browser with a URL `localhost:port/submit/index.html` and you can see the port there.

**Comment by DSLituiev** [comment]
I was running it on a server
