### ISSUE TITLE
CADD annotator not working!

### ISSUE THREAD

**Issue by tkmamidi** [KarchinLab/open-cravat#157]
Firstly, I really love the tool. Thanks for making it!

I'm trying to annotate variants on the web server. In the list of annotators, I can only see CADD Exome but in the store there is generic CADD as well as CADD Exome. Upon testing some variants, I cannot see CADD scores for intron variants. Is there a way to add CADD to the list of annotators?

Thanks!

**Comment by kmoad** [comment]
We've released CADD on the web server. Thanks for finding this.
