### ISSUE TITLE
new windows installer [2.4.0]

### ISSUE THREAD

**Issue by zuber-bioinfo** [KarchinLab/open-cravat#163]
Need to update existing windows-based OC 2.2.7.
Please provide the new windows installer package for V2.4.0.
or any way to update or transfer it to WSL - conda based?

**Comment by kmoad** [comment]
The new windows installer for version 2.4.1 is out on the release page now.

https://github.com/KarchinLab/open-cravat/releases/tag/2.4.1

You'll have to uninstall 2.2.7 before installing 2.4.1. Should be doable with the windows Add/Remove programs menu.
