### ISSUE TITLE
Can not copy from Variant Annotation table

### ISSUE THREAD

**Issue by diekhans** [KarchinLab/open-cravat#165]
I am trying to copy a transcript name from the Variant Annotation table with Firefox/Mac.

One can select the text in the cell.  Instead, the cell becomes yellow with a darker border as if one
can type something in it.  This behavior is non-standard and confusing.

**Comment by kmoad** [comment]
We haven't been able to reproduce this. Tried on a mac running Big Sur in firefox and chrome, and on a linux box running firefox.

Copying from the table should work by selecting a cell and pressing ctrl-c. Should also be possible to select multiple cells by clicking and dragging on the table. Does that work?

Regarding the colors/borders. I agree that the thick border implies the cell is editable like in excel. We can look into changing the styling.
