### ISSUE TITLE
CRAVAT uses GENCODE/Ensembl, however IGV has refseq

### ISSUE THREAD

**Issue by diekhans** [KarchinLab/open-cravat#168]
The embedded IGV has RefSeq gene track.  It would be good to have options to use GENCODE, also subsets of gencode (basic, MANE)

**Comment by kmoad** [comment]
Agree with this. We can switch to using the GENCODE gene track.

**Comment by jasminebro** [comment]
@kmoad is this switch still in progress?

**Comment by kmoad** [comment]
IGV widget with version >=1.2.0 has Gencode transcript by default now.
