### ISSUE TITLE
integrate with desktop igv

### ISSUE THREAD

**Issue by diekhans** [KarchinLab/open-cravat#169]
Integrating with both web and desktop CRAVAT with desktop IGV would help people already using IGV sessions on their own data

**Comment by jasminebro** [comment]
Thank you for the recommendation! @diekhans I will pass this information to the rest of the team.

**Comment by kmoad** [comment]
Integrating with desktop IGV isn't currently in scope. We've added more tracks to the IGVjs widget available in the variant tab. If users are working with bam files, it's possible to add them to that widget to view raw reads.
