### ISSUE TITLE
custom port and host not working

### ISSUE THREAD

**Issue by systxix** [KarchinLab/open-cravat#17]
**We are trying to use open-cravat from remote computer.**

Host computer OS where open-cravat is installed: Windows 10 Enterprise
Host computer name where open-cravat is installed: cravat
Host computer domain: example.com

**For that we installed multiuser support via WinPython Command Prompt as admin:**
pip install open-cravat-multiuser

**After that we changed open-cravat config:**
Config file location: C:\open-cravat\conf\cravat.yml

converter: converter
genemapper: hg38
aggregator: aggregator
reporter: excelreporter
gui_host: www.cravat.example.com
gui_port: 80

**After that we opened firewall port for TCP 80 from cravat host.**

**Now run open-cravat from WinPython Command Prompt as admin:**
wcravat --multiuser --donotopenbrowser

**No matter what gui_host or gui_port is defined output is same:**
C:\Program Files (x86)\open-cravat\scripts>wcravat --multiuser --donotopenbrowser
OpenCRAVAT is served at localhost:8060
(To quit: Press Ctrl-C or Ctrl-Break if run on a Terminal or Windows, or click "Cancel" and then "Quit" if run through OpenCRAVAT app on Mac OS)

**open-cravat is running only in localhost:8060 and is inaccessible from remote computers as http://cravat.example.com**

What im i missing?

**Comment by kmoad** [comment]
Hi Systix,

Thanks for trying open-cravat. Sorry you've run into difficulty. The `gui_host` and `gui_port` settings should be moved to `C:\open-cravat\conf\cravat-system.yml`. We'll be updating the documentation to show this.

**Comment by kmoad** [comment]
@systxix Just to follow up, did this solve the issue?

**Comment by systxix** [comment]
> @systxix Just to follow up, did this solve the issue?

It worked! Thanks!

**Comment by EugeneEA** [comment]
First - thanks for the excelent tool, it seems as exactly what I was looking for.

Also I experience following problem: I'm running cravat on remote server (which works, at least with buildin example) and then want to analyse output on my local machine via SHH tunel. 
I've managed to launch python server on the remote machine with "oc gui example_input.sqlite" comand, and open cravat in my browser on local machne. Newertheless, I do not see the processed file in gui -- the interface is empty. I'm not sure what I'm doing wrong, so any advice will be appriciated.

Best, Eugene

**Comment by rkiminsilico** [comment]
Hi Eugene, there are different methods to do so, depending on how you ran the job. Did you use the command line to run the job on the remote server, or did you use the OpenCRAVAT GUI to run the job?

**Comment by EugeneEA** [comment]
I used command line interface on the server and worked with files there. BTW - I do not know how to run a job via gui, with CROVAT running on a remote server (and files stored at the remote server), as far as "add input file(s)" button links to my local environment. I probably might be able to attach server environment as a local disk or something, but I did not dig in to this so far (also, it would be my second question).

**Comment by rkiminsilico** [comment]
Indeed the OpenCRAVAT GUI on the remote server will ask your local files as input. If you can find the input files on the remote server on the file explorer which appears when you click "add input file(s)" button (by attaching the remote server location as a network drive, for example), that may work.

Other options are:

1. You can download the sqlite file to your local machine and run `oc gui <path to the sqlite file>` to launch the result viewer locally, if OpenCRAVAT is installed on your local machine. 

2. You can convert the job into a GUI job. Run `oc util result2gui <path to the sqlite file>` and run `oc gui --headless` on the remote server. Then, connect to the OC GUI using a web browser on your local machine. A new job will appear on the job list. The ID of the job will the timestamp of your running `oc util result2gui` command. Click "Open result viewer" to see the result.

3. Run `oc gui --headless <path to the sqlite file>` on the remote server. The command will show you the port number. In a web browser on your local machine, open the URL `<remote server hostname>:<port number>/result/index.html?dbpath=<path to the sqlite file in the remote server>`. Use HTTP or HTTPS depending on the remote server's setup.

Let me know if any of the above works for you.

**Comment by EugeneEA** [comment]
Thanks a lot! 

2 and 3 worked pefectly, also in 2 you have to use "send-gui" not the "result2gui"
It would be usefull to include that in the docs (if it is there I did not found it )

Eugene

**Comment by rkiminsilico** [comment]
Great. We'll make sure that the command is on the Wiki.
