### ISSUE TITLE
aiohttp 4.0.0 issue

### ISSUE THREAD

**Issue by BnetButter** [KarchinLab/open-cravat#174]
`pip3 install setup.py develop`
`oc gui`

There won't be an obvious error because it's happening in asyncio task. To see the error, add this

line 406 in `cravat_web.py`

task = loop.create_task(self.start())
task.add_done_callback(lambda task: print(task.exception()))

aiohttp 4.0.0 removes the "loop" keyword argument.

**Comment by kmoad** [comment]
Next release restricts aiohttp version to <4.0.0. We will work on migrating to aiohttp 4.0.0 when it's released.

https://github.com/KarchinLab/open-cravat/commit/44e41bcf780a3be01fb2ea4598862b7e5ebb8060
