### ISSUE TITLE
System update message not legible on upper right of Jobs page

### ISSUE THREAD

**Issue by RachelKarchin** [KarchinLab/open-cravat#177]
![Screenshot 2023-08-24 at 6 03 29 PM](https://github.com/KarchinLab/open-cravat/assets/12953556/92f89f6e-0a59-42b4-871e-06c4a57822a2)

**Comment by RachelKarchin** [comment]
The underlined red link does not do a system update. It goes to the OpenCRAVAT github.

**Comment by kmoad** [comment]
This is fixed in 2.4.1 (latest release)
