### ISSUE TITLE
Error installing base modules via command line...

### ISSUE THREAD

**Issue by CypherAce** [KarchinLab/open-cravat#18]
I've had issues getting the gui/webserver to work so I switched to just going straight command line. As a matter of best practices I setup a new virtual environment(python 3.7.4 and latest pip version) for a fresh install of open cravat. When I try to run:
`cravat-admin install-base`
After installing open cravat via pip I'm getting this output:
`Traceback (most recent call last):
  File "/home/paul/Work/opencravat/ocrav/bin/cravat-admin", line 8, in <module>
    sys.exit(main())
  File "/home/paul/Work/opencravat/ocrav/lib/python3.7/site-packages/cravat/cravat_admin.py", line 693, in main
    args.func(args) 
  File "/home/paul/Work/opencravat/ocrav/lib/python3.7/site-packages/cravat/cravat_admin.py", line 393, in install_base
    install_modules(args)
  File "/home/paul/Work/opencravat/ocrav/lib/python3.7/site-packages/cravat/cravat_admin.py", line 277, in install_modules
    matching_names = au.search_remote(*args.modules)
  File "/home/paul/Work/opencravat/ocrav/lib/python3.7/site-packages/cravat/admin_util.py", line 378, in search_remote
    for module_name in list_remote():
  File "/home/paul/Work/opencravat/ocrav/lib/python3.7/site-packages/cravat/admin_util.py", line 356, in list_remote
    return sorted(list(mic.remote.keys()))
AttributeError: 'str' object has no attribute 'keys'
`

**Comment by kmoad** [comment]
Hi CypherAce, thanks for using OpenCRAVAT. We're currently having issues with our DNS provider for the url that hosts the modules. Basically, http://karchinlab.org/cravatstore is pointing to the wrong ip. We're working on this right now and it should get resolved pretty quickly. I'll update you here when it is.

In the meantime, if you want to continue installing modules, you could set the module server url to directly connect to the right ip. Run `cravat-admin show-system-conf`, and in the first line of the output, there will be a path to a .yml file. Edit that file and change the `store_url` value to `http://128.220.76.147/cravatstore` and OpenCRAVAT should work normally. I'll update you here when the dns issues are resolved and it's safe to change it back.

Also, what issues were you having with the gui/webserver? We'd like to fix those as well.

**Comment by kmoad** [comment]
The DNS issues should be fixed now. If you changed the config, please reset it to `http://karchinlab.org/cravatstore`.

**Comment by CypherAce** [comment]
Its currently in the process of downloading everything but when that's finished I'll change it back. That said, I'm assuming the current issue of not seeing the store tab or any current available annotations is/was related to the DNS... However, prior to this I had an issue where I wouldn't see all the annotations I had installed as available to use when I uploaded a file to run and valid TSVs that would work when run at the command line would hang in the gui... That said my lab manager already submitted a detailed bug/error report on that issue so it's possible its already been fixed or is being addressed. I just haven't gotten around to using the software since then and defaulted to command line just because I'm used to it and was in a hurry.

**Comment by kmoad** [comment]
Yes, The issue of not seeing the store tab, or the current annotators was a result of the DNS problem. We'll look for the bug report from your lab manager about gui issues. I don't see it on the github right now. Do you know if it was in an email?

**Comment by CypherAce** [comment]
Yes, I believe it was via email.
