### ISSUE TITLE
S3 error: The specified bucket does not exist

### ISSUE THREAD

**Issue by tkmamidi** [KarchinLab/open-cravat#185]
![image](https://github.com/KarchinLab/open-cravat/assets/41593805/09d47e78-abcb-4802-94a6-7837db5953f6)

**Comment by kmoad** [comment]
We're working on updated instructions for how to run oc over CloudFormation.

**Comment by jasminebro** [comment]
https://open-cravat.readthedocs.io/en/latest/Cloud.html
