### ISSUE TITLE
Annotator version for API 

### ISSUE THREAD

**Issue by tkmamidi** [KarchinLab/open-cravat#186]
Hi,
Is there a way to specify annotator version from API to query data? This will prevent our downstream pipeline from failing cause of version changes.
Thanks!

**Comment by kmoad** [comment]
Only one version of an annotator can be installed at a time. The run.opencravat.org website is kept up-to-date with the latest version of all annotators.

If you need a specific version, you'd have to use a local installation. Then the command to specify the version to install is 
```
oc module install ModuleName --version 1.2.3
```

To see what versions of a module are available, and the history of changes, run

```
oc module info ModuleName
```
