### ISSUE TITLE
opencravat.org: website’s certificate is expired

### ISSUE THREAD

**Issue by selkamand** [KarchinLab/open-cravat#195]
Thanks for your work on this tool!

Just flagging that navigating to the opencravat landing page (https://opencravat.org/) leads to the following warning indicating the websites certificate may be expired

<img width="1052" alt="image" src="https://github.com/KarchinLab/open-cravat/assets/73202525/8abbb3d5-f9ac-4a3a-9634-dff4bab9fc10">

Apologies if this is the wrong place to report this issue. If this is the case, could you point me to the more appropriate contact-point?

Last checked: 13 November; 10:15pm AEST.
Browser: Firefox

**Comment by kmoad** [comment]
We had an issue with letsencrypt and https cert renewal. It's been fixed now. Sorry for the problems.
