### ISSUE TITLE
multiuser server

### ISSUE THREAD

**Issue by systxix** [KarchinLab/open-cravat#20]
Hi!

What is recommended solution to run opencravat multiuser server on Windows Server 2016 startup/background without user logging in (as a service)?

**Comment by rkiminsilico** [comment]
Hi systxix, thanks for your interest in OpenCRAVAT. We have not tried such a use case yet. We will examine options and get back to you. Meanwhile, have you tried installing Windows installer version of OpenCRAVAT (https://github.com/KarchinLab/open-cravat/wiki/1.-Installation-Instructions#open-cravat-installation-instructions) and running "C:\Program Files (x86)\open-cravat\wcravat.bat" as a Scheduled Task? (https://stackoverflow.com/a/421226) Just off the top of my head.

**Comment by kmoad** [comment]
Systic,

I've had some success with the following process:

Download [Non-Sucking Service Manager](http://nssm.cc/download). Get nssm 2.24-101-g897c7ad, not plain 2.24. Unzip it somewhere and open a shell there.
Use the powershell cmdlet `Get-Command wcravat` or cmd.exe's `where wcravat` to find the path of the wcravat.exe binary.
From the nssm root directory, run `win64\nssm.exe install OpenCRAVAT [wcravat.exe path] --multiuser`. This should create a service that you can then use services.msc to edit to run at startup.

**Comment by systxix** [comment]
OpenCRAVAT doesn't have wcravat.exe 
wcravat.bat is not working with nssm or windows built in sc create command.

**Comment by kmoad** [comment]
It sounds like you're using the windows installer based open-cravat, which, as you noticed, relies on bat files. I also haven't been able to get wcravat.bat to run using nssm. However, OpenCRAVAT 1.7.0, which was released yesterday, seems to have a working path.

Please understand that running OpenCRAVAT as a Windows service isn't something we have an official path for right now, so there may be some discrepancies between what worked on my Windows machine vs yours.

1. Install OpenCRAVAT 1.7.0 from http://karchinlab.org/opencravat/installers/open-cravat-1.7.0.exe. You may want to uninstall the previous version before this.
2. The windows package doen't currently include multiuser support in the server out of the box. We're considering adding it to the next version. It can be added to the current version though. Run the following .bat as admin.
```bat
@echo off
setlocal
set PATH=C:\Program Files (x86)\open-cravat\python-3.7.2.amd64;C:\Program Files (x86)\open-cravat\python-3.7.2.amd64\Scripts;%PATH%
python -m pip install open-cravat-multiuser
endlocal
```
3. 1.7.0 centralizes all OpenCRAVAT commands into one root command called `oc`. Older commands like `wcravat` are still available, but `oc` works for this case, while `wcravat` doesn't. First, we need to allow OpenCRAVAT through the firewall. In `C:\open-cravat\conf\cravat-system.yml`, set `gui_host` to the computer name and `gui_port` to your desired port (probably 80). Then run `oc gui --multiuser`. This will bring up a firewall prompt. Allow the program through the firewall, then ctrl-c to exit the server.
4. In an administrator powershell/cmd window run `nssm.exe install OpenCRAVAT 'C:\Program Files (x86)\open-cravat\oc.bat' gui --multiuser`. If you already have a service called OpenCRAVAT from previous attempts, it can be removed by running `sc delete OpenCRAVAT` in an administrator cmd shell (not powershell) and restarting the machine.

When you restart the machine, the service should run automatically, and you should be able to access OpenCRAVAT from another machine on the network.

Please let me know if this is successful.
