### ISSUE TITLE
Error in IGV widget

### ISSUE THREAD

**Issue by RachelKarchin** [KarchinLab/open-cravat#200]
https://run.opencravat.org/result/index.html?job_id=231205-022508

![image](https://github.com/KarchinLab/open-cravat/assets/12953556/ed1de221-28fc-4444-9f1b-7d43f6323bd3)

hg19

**Comment by kmoad** [comment]
It looks like CORS prevented loading data from goldenPath. wgigv has been updated to load data from karchinlab.org instead, where we control CORS. This won't affect people using oc on their local machines.
