### ISSUE TITLE
Variant Conversion

### ISSUE THREAD

**Issue by jwehr618** [KarchinLab/open-cravat#203]
Hi,

Could you look into variant conversion such as how TransVar processes variants? This would be for when we get NGS reports without genomic coordinates, just the amino acid change and/or c.DNA change. This would be helpful as I am currently running these variants through TransVar first to get genomic coordinate information to then feed into OpenCravat. 

Thanks

**Comment by kmoad** [comment]
We are working on support for HGVS c. input in both jobs and the single variant page. Reverse mapping p. is trickier, but could probably be done by integrating transvar. We'll update this issue with the c. progress. Probably won't support p. on the single-variant page, but could support it through regular jobs.

**Comment by kmoad** [comment]
Update: we plan to release c. and p. support for jobs and on the single variant report within the next few months. We think this will handle your use case.

**Comment by skanderson** [comment]
@jwehr618  With [release 2.6.1](https://github.com/KarchinLab/open-cravat/releases/tag/2.6.1), support for HGVS c. and g. representations has been added as an input for OpenCravat. You can see the example input in the GUI or check out single HGVS variants on our [Single Variant Report](https://run.opencravat.org/webapps/variantreport/index.html). Let us know if this simplifies your workflow and if there is anything we can add or improve.
