### ISSUE TITLE
ValueError: could not convert string to float: '[0.5]'

### ISSUE THREAD

**Issue by joshua-gould** [KarchinLab/open-cravat#21]
```
conda create --name cravat
conda activate cravat
conda install pip
pip install open-cravat
oc module install --yes clinvar vcfreporter vcf-converter hg38
wget https://raw.githubusercontent.com/vcflib/vcflib/master/samples/sample.vcf
oc run sample.vcf -t vcf -l hg38
```

**Comment by kmoad** [comment]
Hi Joshua,

Could you send the rest of the stdout and the content of sample.vcf.log if available?

**Comment by kmoad** [comment]
Hi Joshua,

Could you send the content of sample.vcf.log if available? When I ran the above steps, I got a different exception before reporter ran. Also, is your wget url in fact the raw text of sample.vcf at https://raw.githubusercontent.com/vcflib/vcflib/master/samples/sample.vcf ?

**Comment by joshua-gould** [comment]
You're right, my URL for the vcf was incorrect. It should be https://raw.githubusercontent.com/vcflib/vcflib/master/samples/sample.vcf. Now I get a different error:

2020/02/13 07:05:10 cravat               started: Thu Feb 13 07:05:10 2020
2020/02/13 07:05:10 cravat               conf file: None
2020/02/13 07:05:10 cravat               input files: /Users/jgould/Downloads/sample.vcf
2020/02/13 07:05:10 cravat               input assembly: hg38
2020/02/13 07:05:10 cravat.converter     started: Thu Feb 13 07:05:10 2020
2020/02/13 07:05:10 cravat.converter     input files: /Users/jgould/Downloads/sample.vcf
2020/02/13 07:05:10 cravat.converter     input format: vcf
2020/02/13 07:05:10 cravat.converter     NoneType: None
2020/02/13 07:05:10 cravat.converter     error lines: 0
2020/02/13 07:05:10 cravat.converter     finished: Thu Feb 13 07:05:10 2020
2020/02/13 07:05:10 cravat.converter     num input lines: 9
2020/02/13 07:05:10 cravat.converter     runtime: 0.003
2020/02/13 07:05:10 cravat.mapper        input file: /Users/jgould/Downloads/sample.vcf.crv
2020/02/13 07:05:10 cravat.mapper        mapper database: /Users/Shared/open-cravat/modules/mappers/hg38/data/hg38.sqlite
2020/02/13 07:05:10 cravat.mapper        started: Thu Feb 13 07:05:10 2020
2020/02/13 07:05:10 cravat.mapper        finished: Thu Feb 13 07:05:10 2020
2020/02/13 07:05:10 cravat.mapper        runtime:  0.044
2020/02/13 07:05:10 cravat               num_workers: 15
2020/02/13 07:05:11 cravat.clinvar       started: Thu Feb 13 07:05:11 2020
2020/02/13 07:05:11 cravat.clinvar       finished: Thu Feb 13 07:05:11 2020
2020/02/13 07:05:11 cravat.clinvar       runtime: 0.007s
2020/02/13 07:05:13 cravat.aggregator    level: variant
2020/02/13 07:05:13 cravat.aggregator    input directory: /Users/jgould/Downloads
2020/02/13 07:05:13 cravat.aggregator    started: Thu Feb 13 07:05:13 2020
2020/02/13 07:05:13 cravat               An unexpected exception occurred.
Traceback (most recent call last):
  File "/opt/anaconda3/envs/cravat/lib/python3.8/site-packages/cravat/cravat_class.py", line 375, in main
    self.result_path = self.run_aggregator()
  File "/opt/anaconda3/envs/cravat/lib/python3.8/site-packages/cravat/cravat_class.py", line 761, in run_aggregator
    v_aggregator.run()
  File "/opt/anaconda3/envs/cravat/lib/python3.8/site-packages/cravat/aggregator.py", line 141, in run
    for lnum, line, rd in reader.loop_data():
  File "/opt/anaconda3/envs/cravat/lib/python3.8/site-packages/cravat/inout.py", line 120, in loop_data
    out[col_name] = float(tok)
ValueError: could not convert string to float: '[0.5]'
2020/02/13 07:05:13 cravat               finished with an exception: Thu Feb 13 07:05:13 2020
2020/02/13 07:05:13 cravat               runtime: 2.901s

**Comment by rkiminsilico** [comment]
Hi Joshua,

vcf-converter 1.2.10 has been published with a fix for the issue you had. Can you try `oc module install vcf-converter -v 1.2.10` and run the job again?

**Comment by joshua-gould** [comment]
I now get a different error:

2020/02/13 14:37:20 cravat               started: Thu Feb 13 14:37:20 2020
2020/02/13 14:37:20 cravat               conf file: None
2020/02/13 14:37:20 cravat               input files: /Users/jgould/sample.vcf
2020/02/13 14:37:20 cravat               input assembly: hg38
2020/02/13 14:37:20 cravat.vcfreporter   started: Thu Feb 13 14:37:20 2020
2020/02/13 14:37:20 cravat               no such table: info
Traceback (most recent call last):
  File "/opt/anaconda3/envs/cravat/lib/python3.8/site-packages/cravat/cravat_class.py", line 875, in run_reporter
    await reporter.run()
  File "/opt/anaconda3/envs/cravat/lib/python3.8/site-packages/cravat/cravat_report.py", line 346, in run
    if self.setup() == False:
  File "/Users/Shared/open-cravat/modules/reporters/vcfreporter/vcfreporter.py", line 33, in setup
    self.cursor2.execute(q)
sqlite3.OperationalError: no such table: info
2020/02/13 14:37:20 cravat               finished with an exception: Thu Feb 13 14:37:20 2020
2020/02/13 14:37:20 cravat               runtime: 0.368s

**Comment by rkiminsilico** [comment]
Please try giving `--repeat converter` option to your run. The run did not do vcf-converter.

**Comment by joshua-gould** [comment]
Running the following command works. Thanks.
```
oc run sample.vcf --repeat converter -t vcf -l hg38
```

**Comment by rkiminsilico** [comment]
Great! Let us know if you encounter any issue.
