### ISSUE TITLE
python 3.12 module imp deprecated

### ISSUE THREAD

**Issue by Kaddea** [KarchinLab/open-cravat#214]
Just a short info that the module "imp" is deprecated in python 3.12 (ubuntu 24.04 noble).

"import imp" in site-packages/cravat/cravat_web.py (line 10) can be removed (importlib is imorted later anyway)

and in site-packages/cravat/webresult/webresult.py (line 6) it needs to be extendet to "import importlib"

there is still one syntax warning 
site-packages/cravat/webresult/webresult.py:270: SyntaxWarning: invalid escape sequence '\_'
  q = 'select * from info where colkey not like "\_%" escape "\\"'

but it's running fine so far :)

**Comment by kmoad** [comment]
Ah, we've been building on 3.11. We'll test it out on 3.12. Thanks for the catch!
