### ISSUE TITLE
vcfreporter does not work when input vcf is gzipped

### ISSUE THREAD

**Issue by joshua-gould** [KarchinLab/open-cravat#22]
```
oc run test.vcf.gz --repeat converter -t vcf -l hg38 -d .
```

  File "/opt/anaconda3/envs/cravat/lib/python3.8/site-packages/cravat/cravat_report.py", line 240, in run_level
    self.write_preface(level)
  File "/Users/Shared/open-cravat/modules/reporters/vcfreporter/vcfreporter.py", line 91, in write_preface
    for line in f:
  File "/opt/anaconda3/envs/cravat/lib/python3.8/codecs.py", line 322, in decode
    (result, consumed) = self._buffer_decode(data, self.errors, final)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x8b in position 1: invalid start byte

**Comment by rkiminsilico** [comment]
Hi Joshua, thanks for letting us know. vcf-reporter assumes the input file to be a plain text file (to transfer existing annotations in the input file to the new vcf format report file). We'll make a new version of vcf-reporter which can handle compressed input files, also.

**Comment by rkiminsilico** [comment]
@joshua-gould vcfreporter 1.0.13 has been published which can handle vcf.gz input files. Can you install (`oc module update vcfreporter`) and try it?

**Comment by joshua-gould** [comment]
Thanks, I've confirmed that it works.
