### ISSUE TITLE
vest and chasmplus: report FDR

### ISSUE THREAD

**Issue by joshua-gould** [KarchinLab/open-cravat#24]
In addition to reporting the p-value, can you also please output the FDR? Thanks.

**Comment by rkiminsilico** [comment]
The current OpenCravat software architecture relies on fetching pre-computed annotations one variant at a time. FDR calculations depend on the entire user-submitted data in a run, so it cannot be pre-computed. However, we are currently working on incorporating FDR calculations computed “on the fly” for both VEST and CHASMplus.
