### ISSUE TITLE
Dependency issues in module update after 1.8.0

### ISSUE THREAD

**Issue by kmoad** [KarchinLab/open-cravat#27]
Hm - this is tricky:
To hide the yaml warnings I had redirected stderr in a wrapper script.  After install of 1.8.0, ocwrapper module update listed four things to update.  Then nothing.  For a really long time - until I clued in.  Not sure I agree with the use of both stdout and stderr in the same breath?
Then a slew of fun of our own making - a nasty permissions thing. Redo the install/update.Then a trial -expect nothing - run of oc module update:
oc module update
Newer versions of (cravat-converter, oldcravat-converter, vcf-converter) are available, but would break dependencies. You may use --strategy=force to force installation.
No module updates are needed

I _think_ we're good, but a little shakey. (I don't use oc, I'll pester she-who-does to try it asap)

_Originally posted by @iceback in https://github.com/KarchinLab/open-cravat/issues/26#issuecomment-620345299_

**Comment by kmoad** [comment]
@iceback New issue here for the dependency thing.

Could you send me the output of oc module ls -i. It'll probably be a quite a few lines. I'm going to recreate your installed modules and versions to see what's causing dependency issues.

**Comment by iceback** [comment]
Sure, give me a second

**Comment by iceback** [comment]
Trouble today:
2020/04/28 12:07:31 cravat               Input format could not be determined for file Batch1and3-joint.raw.SGS_regions.filteredInd.vcf.gz. Additional input format converters are available. View available converters in the store or with "oc module ls -a -t converter"

ocDriver module ls -a -t converter
Name                     Title                      Type         Installed    Up to date    Store latest ver    Store data source ver    Local ver    Local data source ver    Size
23andme-converter        23andMe Converter          converter                               1.3.1                                                                              15.7 kB
ancestrydna-converter    AncestryDNA Converter      converter                               1.3.1                                                                              27.4 kB
cravat-converter         Cravat Converter           converter    yes                        1.1.2                                        None                                  9.2 kB
dbsnp-converter          dbSNP Converter            converter                               1.1.1               153                                                            28.7 GB
ftdna-converter          FamilyTreeDNA Converter    converter                               1.3.1                                                                              28.4 kB
oldcravat-converter      OldCravat Converter        converter    yes                        1.1.2                                        None                                  7.6 kB
vcf-converter            VCF Converter              converter    yes                        1.4.2                                        None                                  48.9 kB

**Comment by kmoad** [comment]
It looks like a few modules only partially installed. One of them was vcf-converter, which is why the vcf file was not processed properly. The one's that partial installed have `None` as a version in moduleListing.txt. To fix it in your installation, run `oc module uninstall XXXXX && oc module install XXXXX` for the `None` version modules.

I expect this was caused when you cancelled the update. Normally, this would delete the module that was mid-install, but it seems like there was some corner case here that prevented it. We'll try to track it down and make the partial handling more robust next version.

**Comment by iceback** [comment]
Likely story😏. Will get those reloaded ASAP

**Comment by iceback** [comment]
Yes!  uninstalled, installed and things look good.  Waiting for confirmation from the real user, but thanks for your help.
