### ISSUE TITLE
Error while runnin OC on window paltform

### ISSUE THREAD

**Issue by amarinderthind** [KarchinLab/open-cravat#273]
Error log
 

> 2024/06/21 15:20:42 cravat               input assembly: hg38

2024/06/21 15:20:42 cravat               version: open-cravat 2.4.1 C:\Program Files\OpenCRAVAT\python\lib\site-packages\cravat
2024/06/21 15:20:42 cravat               version: cadd_exome 1.6.1 C:\open-cravat\modules\annotators\cadd_exome
2024/06/21 15:20:42 cravat               version: cgc 99.0.0 C:\open-cravat\modules\annotators\cgc
2024/06/21 15:20:42 cravat               version: cgl 1.1.0 C:\open-cravat\modules\annotators\cgl
2024/06/21 15:20:42 cravat               version: encode_tfbs 1.0.2 C:\open-cravat\modules\annotators\encode_tfbs
2024/06/21 15:20:42 cravat               version: genehancer 1.1.0 C:\open-cravat\modules\annotators\genehancer
2024/06/21 15:20:42 cravat               version: mirbase 1.0.1 C:\open-cravat\modules\annotators\mirbase
2024/06/21 15:20:42 cravat               version: mutpanning 1.0.0 C:\open-cravat\modules\annotators\mutpanning
2024/06/21 15:20:42 cravat               version: ncrna 2022.12.12 C:\open-cravat\modules\annotators\ncrna
2024/06/21 15:20:42 cravat               version: hg38 1.11.0 C:\open-cravat\modules\mappers\hg38
2024/06/21 15:20:42 cravat.converter     started: Fri Jun 21 15:20:42 2024
2024/06/21 15:20:42 cravat.converter     Input file(s): C:\open-cravat\jobs\default\240621-151850\CSCC_0016-P1.purple.somatic.vcf, C:\open-cravat\jobs\default\240621-151850\CSCC_0017-P1.purple.somatic.vcf, C:\open-cravat\jobs\default\240621-151850\CSCC_0018-P1.purple.somatic.vcf, C:\open-cravat\jobs\default\240621-151850\CSCC_0026-P1.purple.somatic.vcf, C:\open-cravat\jobs\default\240621-151850\CSCC_0029-P1.purple.somatic.vcf, C:\open-cravat\jobs\default\240621-151850\CSCC_0137-P1.purple.somatic.vcf, C:\open-cravat\jobs\default\240621-151850\CSCC_0141-P1.purple.somatic.vcf, C:\open-cravat\jobs\default\240621-151850\CSCC_0160-P1.purple.somatic.vcf
2024/06/21 15:20:46 cravat.converter     input format: vcf
2024/06/21 15:35:52 cravat.converter     error lines: 0
2024/06/21 15:35:52 cravat.converter     finished: Fri Jun 21 15:35:52 2024
2024/06/21 15:35:52 cravat.converter     num input lines: 5261653
2024/06/21 15:35:52 cravat.converter     runtime: 906.004
2024/06/21 15:35:52 cravat               num_workers: 25
2024/06/21 15:35:56 cravat               input line chunksize=208721 total number of input lines=5218035 number of chunks=25
2024/06/21 15:40:19 cravat               An unexpected exception occurred.
Traceback (most recent call last):
  File "C:\Program Files\OpenCRAVAT\python\lib\site-packages\cravat\cravat_class.py", line 567, in main
    self.populate_secondary_annotators()
  File "C:\Program Files\OpenCRAVAT\python\lib\site-packages\cravat\cravat_class.py", line 1172, in populate_secondary_annotators
    self._find_secondary_annotators(module, secondaries)
  File "C:\Program Files\OpenCRAVAT\python\lib\site-packages\cravat\cravat_class.py", line 1197, in _find_secondary_annotators
    ret[sannot.name] = sannot
AttributeError: 'NoneType' object has no attribute 'name'
2024/06/21 15:40:19 cravat               finished with an exception: Fri Jun 21 15:40:19 2024
2024/06/21 15:40:19 cravat               runtime: 1178.235s`

**Comment by kmoad** [comment]
The `encode_tfbs` annotator requires that another annotator, `hg19` be installed. It should have been automatically downloaded with `encode_tfbs`. But you can manually fix that with `oc module install hg19`.

Because of datacenter maintenance this week, you'll have to change the module store location by following instructions [here](https://open-cravat.readthedocs.io/en/latest/getting_started_web.html#installing-opencravat-via-installer-local).
