### ISSUE TITLE
Automatically load BAM files

### ISSUE THREAD

**Issue by chadisaad** [KarchinLab/open-cravat#28]
Is it possible to load automatically a corresponding BAM file with IGV widget in order to visualize the variant ? Instead of loading it manually each time I open an VCF.

**Comment by rkiminsilico** [comment]
OpenCRAVAT does not have such a feature, but it may be possible to implement it. Do you mean something like this?: Open a job result viewer -> load a bam file on the IGV viewer -> save the result viewer state -> close the result viewer -> later, open the result viewer for the same job -> the same bam file is automatically loaded on the IGV viewer.

**Comment by chadisaad** [comment]
My idea is to load automatically the BAM file corresponding to the VCF file. Without having to click manually on 'load track' and search the file on the file system. The path of the BAM can be the same of the VCF (by changing only the extension) or an metadata in the VCF header..

And of course as you described, to be able to save the viewer state if possible.

**Comment by chrstphdm** [comment]
I'll summarize this feature by the ability to link a BAM file to a job.

The idea would indeed be :
1. Open a job result viewer 
2. load a bam file on the IGV viewer
3. **save the result viewer state** (save the link between the job & the BAM file ?)
4. close the result viewer 

Later :
1. open the result viewer for the same job 
2. the same bam file is automatically loaded on the IGV viewer (by reading the link ?)

Where would this link between job result and BAM file be? 
sqlite base? 
which field ?

In the long term, we would like to be able to use this functionality to generate this field by a script.

Thank you !

**Comment by rkiminsilico** [comment]
Thanks for the detailed explanation. OC currently does not have that feature, but that may be possible. We'll discuss and let you know in this thread.

**Comment by kmoad** [comment]
Sorry for the delayed response. We've discussed this issue internally and unfortunately can't make it work because the browser restricts access to the local disk.
