### ISSUE TITLE
Cannot install module chasmplus_STAD

### ISSUE THREAD

**Issue by anastasiaprime** [KarchinLab/open-cravat#294]
Hello,

I've started using chasmplus, but I have an error when trying to install chasmplus_STAD: 

`oc module install chasmplus_STAD
` 

`ERROR
'LooseVersion' object has no attribute 'version'
Repeat command with --debug for more details
`
When I add --debug I get this: 

Traceback (most recent call last):
  File "/opt/miniconda3/lib/python3.11/site-packages/cravat/oc.py", line 264, in main
    args.func(args)
  File "/opt/miniconda3/lib/python3.11/site-packages/cravat/cravat_admin.py", line 282, in install_modules
    if not args.force and LooseVersion(local_ver) >= LooseVersion(remote_ver):
                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/miniconda3/lib/python3.11/site-packages/setuptools/_distutils/version.py", line 90, in __ge__
    c = self._cmp(other)
        ^^^^^^^^^^^^^^^^
  File "/opt/miniconda3/lib/python3.11/site-packages/setuptools/_distutils/version.py", line 341, in _cmp
    if self.version == other.version:
       ^^^^^^^^^^^^
AttributeError: 'LooseVersion' object has no attribute 'version'

When I do `oc module ls -a -t annotator` I see chasmplus_STAD and I've already install chasmplus_LUAD. Could you help me please?

**Comment by jasminebro** [comment]
@anastasiaprime Hi, I have forwarded this issue to our IT team to troubleshoot.

**Comment by jasminebro** [comment]
Hi @anastasiaprime I am trying to replicate your error and I am not having the same problem. What version of python are you using? Also, what version of mini condo are you using? There seems to be an issue with mini condo and python if the versions do not match up exactly when things are upgraded.

**Comment by anastasiaprime** [comment]
Hi @jasminebro  
I'm not sure what the initial error was, but I have installed chasmplus_STAD successfully today, so the problem was solved somehow. Maybe it's because I recently updated Ubuntu using the command `sudo apt get upgrade`. I'm using python 3.11.9 without conda. Anyway thanks for your response!

**Comment by jasminebro** [comment]
@anastasiaprime most likely it was a versioning issue. Happy to hear you were able to install chasmplus_STAD. Please let us know if you need any further assistance and thank you for using OpenCRAVAT!

If you have 2 minutes, please click on the following link to access our user feedback form: https://tinyurl.com/OpenCRAVATUserSurvey . We are always eager to receive feedback from our users. Happy annotating!
