### ISSUE TITLE
hearbeat timeout sensibility : Lost connection to server

### ISSUE THREAD

**Issue by chrstphdm** [KarchinLab/open-cravat#30]
Hi,

When i'm using a VPN and try to access to my openCravat server, i'm getting a "Lost connection to server\nPlease launch OpenCRAVAT again" popup. This error manifests itself in 2 ways :
1. the popup appears, i can not do anything except refreshing the page
2. sometimes, after waiting few seconds, the error message disappears and loading popup appears. Graphics starts to be filled and few seconds later, "lost connection" popup appears again.

Remarks : 
- Everything's fine without the VPN.
- I do not have any other connexion problems with my VPN.

This is the js console :
![image](https://user-images.githubusercontent.com/7338028/83005477-2393d300-a011-11ea-8deb-963f080bd85c.png)

ping on the webserver show 13ms of latency and no packet lost :
![image](https://user-images.githubusercontent.com/7338028/83005834-9604b300-a011-11ea-85f6-c5fa3b2faa90.png)

Is there a way to increase timeout for heartbeat ?

Let me know if I can add/do some test.
Thank you for your help.

**Comment by rkiminsilico** [comment]
OC with VPN is new to us. Thanks for sharing. 

First, a first-aid measure:

`pip list -v` will show the location of open-cravat folder. In the folder, `websubmit/nocache/websubmit.js` (for job submission and web store page) and `webresult/nocache/js/util.js` have `checkConnection` function (for result viewer). In the function, 
```
if (failures >= 3) {
    setServerStatus(false);
}
```
triggers the pop-up message. Commenting out `setServerStatus(false);` will prevent the popup.

Secondly, in the same function, `ws.onclose = ...` is run whenever the websocket connection to the server is lost. Can you add something like `console.log('connection lost');` inside it and check how soon the lost connection is detected with the developer/javascript console of your browser?

**Comment by chrstphdm** [comment]
Thank you for your support.

After some extended tests with your instructions, I call the network team, it appears to be a firewall rule filtering websockets.

Everything is right now.
Thank you !

**Comment by rkiminsilico** [comment]
Glad to be of help! Let us know any feedback, problems, suggestions, and wish lists on this issue forum or to support@cravat.us.
