### ISSUE TITLE
Filter by gene using the command line version

### ISSUE THREAD

**Issue by BologaAlexandru** [KarchinLab/open-cravat#300]
Hello,

I was wondering if the Gene Filter can be used in command line. I am running oc on a WGS vcf file and my command looks like this:

`oc run file.vcf -l hg19 -a clinvar -t text excel`

The text/excel output contains all genomic variants from the input vcf. Is there a way to generate a similar output but using the Gene Filter too, without open the oc gui? 

I tried to use the filtersqlite option after I saved the filter (a list of genes) from the gui as .json file with the command:

`oc util filtersqlite file.vcf.sqlite -f filter_by_gene.json -s filtered`

Unfortunetly, I couldn't obtain a new text/excel file for my vcf with the Gene Filter applied without using the oc gui. Is this possible? 

Thank you!

**Comment by jasminebro** [comment]
Hi @BologaAlexandru. The `oc report` function is the easiest way to filter without using the GUI. I have shared the documentation for generating a report here ([Generate a Report from a Job](https://open-cravat.readthedocs.io/en/latest/2.-Command-line-usage.html#report-generate-a-report-from-a-job)) 

Can you try this command and let me know if it works? `oc report input.sqlite -f genefilter.json -t excel`

Thank you for using OpenCRAVAT!

**Comment by BologaAlexandru** [comment]
Hello @jasminebro 
Thank you for your answers. The oc report function is working. 

Thank you again! 
Wish you all the best!

**Comment by jasminebro** [comment]
@BologaAlexandru Awesome! Happy to hear it. Please let us know if you need any further assistance and thank you for using OpenCRAVAT!

If you have 2 minutes, please click on the following link to access our user feedback form: https://tinyurl.com/OpenCRAVATUserSurvey . We are always eager to receive feedback from our users. Happy annotating!
