### ISSUE TITLE
sqlite3.OperationalError: near ".": syntax error

### ISSUE THREAD

**Issue by chadisaad** [KarchinLab/open-cravat#31]
Error when an header **ID** contains non-alphanumeric char (like **+** or **.** )

**Example:** 

> #INFO=<ID=**gnomad.exome**,Number=.,Type=String,Description="/GNOMAD/2.1.1/gnomad.exomes.r2.1.1.sites.vcf.gz (exact)">

**Error:**
```
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/cravat/cravat_class.py", line 382, in main
    self.result_path = self.run_aggregator()
  File "/usr/local/lib/python3.6/site-packages/cravat/cravat_class.py", line 905, in run_aggregator
    v_aggregator.run()
  File "/usr/local/lib/python3.6/site-packages/cravat/aggregator.py", line 94, in run
    self._setup()
  File "/usr/local/lib/python3.6/site-packages/cravat/aggregator.py", line 294, in _setup
    self._setup_table()
  File "/usr/local/lib/python3.6/site-packages/cravat/aggregator.py", line 351, in _setup_table
    self.cursor.execute(q)
sqlite3.OperationalError: near ".": syntax error

```

**Comment by grafitos** [comment]
I guess that ID is used as sq3 table name. Table names should be double quoted to allow special characters.

q = 'create table {} ({});'.format(
                self.table_name,
                ', '.join(col_def_strings),
            )

**Comment by rkiminsilico** [comment]
Thanks for the bug report. We did not expect . or any other special characters in table and column names. We'll reflect the double quotation for table and column names in the next release.

**Comment by rkiminsilico** [comment]
@chadisaad As a first-aid measure, I have published vcf-converter:1.4.5 to the store. Can you install it by `oc module update vcf-converter` and try it? 

@grafitos Thanks for the solution.

**Comment by chadisaad** [comment]
It works :) thank you

**Comment by rkiminsilico** [comment]
Great. Closing this issue.

**Comment by rkimoakbioinformatics** [comment]
@chadisaad Hi, thanks for reaching out to us about OpenCRAVAT issues. I hope that OpenCRAVAT is working for you well now. We are conducting interviews to learn what else we could do for genomic variant researchers. Would you be available for such an interview? It will take just about 15 minutes and your input will be invaluable to make OpenCRAVAT even better. It does not have to be about your experience with OpenCRAVAT. We just would like to hear what your experience has been with genomic variant analysis tools. If you would kindly like to, please let me know.
