### ISSUE TITLE
Specify annotation vesrion with `oc module install`

### ISSUE THREAD

**Issue by HuynhNPT** [KarchinLab/open-cravat#316]
Hi! I have more of a question than a bug. 

**Describe the bug**
I'm trying to set up open-cravat on google cloud to be able to run with nextflow. (I don't have access to AWS or Azure, so I can't really use those made-ready cloud platforms). After some trials and errors, I figured the best way to be able to run these nextflow scripst with open-cravat is to install the module into the temp virtual image every time a process is run (a bit inefficient, but it works for now). 

My question then is, supposed I use open-cravat v.2.7.3, will the clinvar annotation version get updated depending on the day the module was pulled? 

For example, will this command result in two different annotation versions if it is run now versus 2 years later, assuming the open-cravat version stays the same? 

```
 oc module install-base
 oc module install -y clinvar
 oc new example-input .
 oc run example_input -l hg38 -a clinvar
```

**Describe the solution you'd like**
I would like to understand the clinvar version being pulled above. Is there a way to specific clinvar version when running `oc module install` or `oc run`?

**Comment by kmoad** [comment]
You can specify a version to install using the `-v/--version` option to `oc module install`. You can see what past versions of an annotator are available with the `oc module info` command.

For example, it could work like this for clinvar, which updates once a month. (I removed some lines of output here for clarity).

```
$ oc module info clinvar
. . .
title: ClinVar
type: annotator
versions:
- 2024.09.01 (data source 2024.09.01) Monthly data update
- 2024.10.01 (data source 2024.10.01) Monthly data update, update test key
- 2024.12.01 (data source 2024.12.01) Monthly data update, update test key
. . .
$ oc module install clinvar --version 2024.09.01
$ oc module ls clinvar
Name     Title    Type       Version     Data source ver  Size      
clinvar  ClinVar  annotator  2024.09.01  2024.09.01       381.9 MB
```

**Comment by HuynhNPT** [comment]
Thank you! Works perfectly.
