### ISSUE TITLE
unable to access to karchinlab.org

### ISSUE THREAD

**Issue by wanghao1991217** [KarchinLab/open-cravat#33]
I'am using the code script:  oc module install-base , how the connection to karchinlab.org was disrupted.

WARNING: Could not list modules from http://karchinlab.org/cravatstore/manifest.yml. Check internet connection.
No modules to install found

**Comment by kpagel** [comment]
Unfortunately, the MARCC systems that host OpenCRAVAT data are down for emergency maintenance. 
Updates will be posted on our Twitter (https://twitter.com/OpenCRAVAT) and the MARCC Twitter (https://twitter.com/marcc_systems).

**Comment by EugeneEA** [comment]
Hi! Hope you'll resolve the situation in the near future and wish you all the luck with it.
Also I'd like to ask: currently I have all he modules which I need installed and command line interface works just fine. However, the web interface now do not have a list of available annotators (see the attached pic) and such behavior seems strange for me (as far as I already have everything locally). Could you please clarify why is so? I can guess that this widget somehow pick up info from the Store which is currently unavailable? Could I change that behavior? 

![cravat](https://user-images.githubusercontent.com/57629300/89412879-7cc66400-d730-11ea-9c3a-737ba49b0dc9.png)

**Comment by kmoad** [comment]
@EugeneEA Sorry that's happening. The annotators select is *supposed* to still work without a connection to the store. At least, it's working on my machine.  Though it does take about 10 seconds to show up on the first launch. Could you send a few more things to help us diagnose this?

1) Could you rerun the web interface with error reporting on using `oc gui --debug` and send me the output on the console
2) What version of oc are you running. Use `oc version` to check, or look in the top right of the gui
3) Are there error messages in the browser's javascript console. [Here are directions for opening it](https://webmasters.stackexchange.com/questions/8525/how-do-i-open-the-javascript-console-in-different-browsers)

**Comment by EugeneEA** [comment]
> @EugeneEA Sorry that's happening. The annotators select is _supposed_ to still work without a connection to the store. Though it does take about 10 seconds to show up on the first launch. Could you send a few more things to help us diagnose this?
> 
> 1. Could you rerun the web interface with error reporting on using `oc gui --debug` and send me the output on the console
> 2. What version of oc are you running. Use `oc version` to check, or look in the top right of the gui
> 3. Are there error messages in the browser's javascript console. [Here are directions for opening it](https://webmasters.stackexchange.com/questions/8525/how-do-i-open-the-javascript-console-in-different-browsers)

>2 - 1.8.0 and here was the problem: I was runing the 1.8 on a remote server. After update to 2.0.1 everything is back to normal, thansk!

**Comment by kmoad** [comment]
@EugeneEA Glad things are working! 2.0.1 does have more resiliency against internet connection loss. Also, karchinlab.org came back online yesterday afternoon (US eastern time)

@wanghao1991217 Module installation should be available again. Sorry about the outage.
