### ISSUE TITLE
port 8080

### ISSUE THREAD

**Issue by emissiaglia** [KarchinLab/open-cravat#34]
I have another app which also requires 8080. As a result, this has to be closed before running openCRAVAT. Is there a way to change the port used by openCRAVAT?
Many thanks for your help

**Comment by kmoad** [comment]
Hi emissiaglia,

You can set the port by adding a line like `gui_port: 8888` to the cravat-system.yml config file. You can find the location of cravat-system.yml by running `oc config system`. The path will be in the first line.
