### ISSUE TITLE
annotation with scondary_data option

### ISSUE THREAD

**Issue by EugeneEA** [KarchinLab/open-cravat#37]
Sorry if it is written somewhere, but I failed to find it.
 
I need to build an annotator, which takes into account results from several other annotators. As fas as I get it - the option seondary_data designed exactly for that purpouse. But I have not found a clear doc on how to use it. I might figure it out from the code, but it'll take some time for me, so I appreciate if you can point me out where to look for the right info. Also I believe that if it's not in the docs now it anyhow should be there.

Best wishes, Eugene

**Comment by EugeneEA** [comment]
Ok, I've figured out how it works more or less, but it turns out that "secondary_data" functionality does not solve my "problem" as far as I can only access results of "base annotators" (hugo, transcript etc..) and not additional ones. 

 I'll elaborate a bit on why I need such a functionality - to create a built-in ACMG annotation for cravat suite.
Currently I have an "intervar" code (https://github.com/WGLab/InterVar) re-written as such it take an open cravat reuluting .tsv and creates ACMG annotation, which is good, but I also, for convenience, wanted to decorate it as an open cravat  annotator. For it to work I need first: to annotate the vcf file with a bunch of other annotators and second: combine the resulting data and produce additional column with the results.

Now I think that it is not possible without major intervention in cravat code :( Am I correct? Is such functionality something worth adding?

Best wishes, Eugene

**Comment by kmoad** [comment]
I've added some documentation about how to use `secondary_data` here https://github.com/KarchinLab/open-cravat/wiki/Annotator-Reference#secondary-inputs

Unfortunately this won't currently let you load in data from `input.vcf.extra_vcf_info.var`, which is where the data from INFO goes during processing. That file is created by the vcf-converter as a "pseudo-annotator". There is a way to hack the data into your annotator though.

In the `setup` method of the annotator, we can read in the contents of the extra info file, then pull from them in the `annotate` method.

Make `annotator.py` something like this

```python
from cravat.inout import CravatReader
import os

class CravatAnnotator(BaseAnnotator):

	def setup(self):
		var_fpath = os.path.join(
		    self.output_dir, 
		    '.'.join([self.output_basename,
		    'fhir_input.var'])
		)
		var_reader = CravatReader(var_fpath)
		self.vcf_info = {row['uid']:row for row in var_reader.get_data()}
		
	def annotate(self, input_data, secondary_data=None):
		vcf_row = self.vcf_info.get(input_data['uid'])
		if vcf_row:
			# Do stuff
			...
```

**Comment by EugeneEA** [comment]
Thansk a lot!

Seems  that it will solve my "problem" after all. I did not digg deep enough and have figured out only default seconday_data behavioure, without modiffication of yml file.

Best, Eugene
