### ISSUE TITLE
unite standars of empty "secondary_data" field

### ISSUE THREAD

**Issue by EugeneEA** [KarchinLab/open-cravat#38]
Hi! It's not a bug report, just a suggestion:

I've noticed that the content of the "secondary_data" variable varies from annotator to annotator when the fields are empty.
Here is an example of rare variant, which absent from the frequencies DBs:

`print(secondary_data['esp6500'])`
>[]

`print(secondary_data['gnomad3'])`
>[{'uid': 1, 'af': None, 'af_afr': None, 'af_asj': None, 'af_eas': None, 'af_fin': None, 'af_lat': None, 'af_nfe': None, 'af_oth': None, 'af_sas': None}]

`print(secondary_data['thousandgenomes'])`
>[{'uid': 1, 'af': None, 'afr_af': None, 'amr_af': None, 'eas_af': None, 'eur_af': None, 'sas_af': None}]

For example clinvar also behave similar to esp6500

This is quite inconvenient to handle and also there is no guarantee that the output format will not change back and forth. 
So It would be awesome to have some convention either to return empty list or dict with Nones (the later makes more sense probably)
And I suppose it's couple lines of the code

Best, Eugene

**Comment by kmoad** [comment]
Thanks for the feedback. I agree that this is annoying. We've added it to our bug tracker to ignore dicts where all the values are `None`.

While we wait for the next version though. It's possible to solve this for each of the modules you're having trouble with. Could you send a list?

**Comment by EugeneEA** [comment]
Awesome, also I can easily wait for the new release.

> We've added it to our bug tracker to ignore dicts where all the values are None.
So you are planning to change all annotators to return empty list if no data present?
I'm currently working with following annotators: 
`gerp, interpro, repeat, clinvar, esp6500, gnomad3, thousandgenomes`
From these Clinvar and esp6500 returns empty lists and the rest list of Nones.

**Comment by kmoad** [comment]
We've updated `gerp, interpro, repeat, gnomad3, and thousandgenomes` so that they will be an empty list in `secondary_data`. You can get the new versions with `oc module update`. Let me know if it works!
