### ISSUE TITLE
tsv compression

### ISSUE THREAD

**Issue by cariaso** [KarchinLab/open-cravat#41]
It should be relatively straightforward to write the tsv to a tsv.gz via a pipe, and often there is a performance gain by reducing the amount of disk IO.

Is this feature compelling or undesirable?

**Comment by kmoad** [comment]
I'd say it's compelling, expecially for tsv and vcf reports. Disk space isn't free. I'd be a bit cautious about doing it by default. For smaller jobs, there's a benefit to being able to just open results straight away. But when the report is intended for downstream processing, no real reason not to. 

There's also the problem of reporters being modular. Some reports such as excel aren't worth gzipping. There could be a flag that says "compress if possible" that reporters could choose what to do with. Would that be enough?

**Comment by cariaso** [comment]
I don't see sufficient utility in compressing the excel file, but for TSV it's quite possible to do most or all downstream processing via "gzip -dc" or similar command line pipes.

**Comment by kmoad** [comment]
A few of these argument paths already exist actually, just there's no compressed argument/config available in them . You can override module configs with `--module-option module.foo=bar`. The same effect can be had with a config yml file `-c conf.yml` where conf.yml is.
```
run:
  module:
    foo: bar
```
But the modules have to explicitly opt to use these values.

So tsv and vcf reporters could add compress options through these pathways without changes to the oc code. 

I think that's the better path in the short term, but we'll kick around the idea of a dedicated "compress the output" flag internally and get back to you.

**Comment by cariaso** [comment]
> I think that's the better path in the short term, but we'll kick around the idea of a dedicated "compress the output" flag internally and get back to you.

I'd discourage kicking around the idea. I dislike it, but based on
> "compress if possible" that reporters could choose what to do with
I thought it might have been your initial preference.
