### ISSUE TITLE
Export filtered table as an excel file

### ISSUE THREAD

**Issue by kokyriakidis** [KarchinLab/open-cravat#43]
Hi! 

I tried to download a filtered table (only chr X variants) as an excel file but there is no option. It exports it as tsv. I can only export the whole table as an excel file. The problem is that having many annotators makes this big excel file unusable.

Is there a way to do that that I have not noticed?

**Comment by rkiminsilico** [comment]
Hi again, currently, exporting to an excel file with filters applied is not possible on the result viewer GUI, but it is being considered for a future release. Meanwhile, there is a couple of workaround. First, make the filter criteria on the result viewer GUI and then save it with the file save icon at the bottom right corner of the Filter tab. Give a name to the filter. Then, on the command-line, run the command
```
sqlite3 xxxxx.sqlite 'select viewersetup from viewersetup where name="<filter name>"'
```
(xxxxx.sqlite as your result database file and <filter name> as the filter save name)
The result will be a string such as
```
{"filterSet":{"sample":{"require":[],"reject":[]},"genes":[],"variant":{"operator":"and","rules":[{"column":"base__so","test":"select","value":["MIS"]},{"column":"base__coding","test":"hasData","negate":false}]},"smartfilter":{"base":{"so":["MIS"],"coding":false}}}}
```
Make a text file such as filter.json with its content being the output of the above sqlite3 command. Save the file, and run
```
oc report xxxxx.sqlite -t excel -f filter.json
```
(replace xxxxx.sqlite and filter.json with your paths. Use -t option of your choice)
to get a filtered excel output, for example.

In the next version of oc, `oc report xxxxx.sqlite -F <filter name> -t excel` will be supported.

Another option is to make the filter.json file yourself. It is a bit more complicated, but if you prefer this way, we can explain, let us know.

**Comment by kmoad** [comment]
What you want in `filter.json` is actually the *value* of "filterSet" in that JSON. So delete  `{"filterSet":` from the start, and the last `}` from the end.
