### ISSUE TITLE
pharmgkb mapping fails to note PA166154339

### ISSUE THREAD

**Issue by cariaso** [KarchinLab/open-cravat#44]
test1.vcf 
```
##fileformat=VCFv4.2
#CHROM  POS     ID      REF     ALT     QUAL    FILTER  INFO    FORMAT  test1
chr11   113400106       .       G       A       1339.06 PASS    AC=2;AF=1;AN=2;DP=432;FS=0;MQ=249.72;QD=3.1;SOR=0.94;FractionInformativeReads=1;VQSLOD=5.35516  GT:AD:AF:DP:F1R2:F2R1:GQ:PL:GP:PRI:SB:MB        1/1:0,432:1:432:0,246:0,186:450:1377,1292,0:450,450,0:0,34.77,37.77:0,0,192,240:0,0,212,220
chr11   113412966       .       C       A       224.21  PASS    AC=2;AF=1;AN=2;DP=59;FS=0;MQ=250;QD=3.8;SOR=2.507;FractionInformativeReads=1;VQSLOD=7.44863     GT:AD:AF:DP:F1R2:F2R1:GQ:PL:GP:PRI:SB:MB        1/1:0,59:1:59:0,26:0,33:174:262,177,0:224.21,174.21,0:0,34.77,37.77:0,0,13,46:0,0,32,27
```

command line

```
oc run test1.vcf --liftover hg38  -x --cleanrun -t text -d out-test1  -a pharmgkb
```

The first record has no identified pharmgkb match, but should match
https://www.pharmgkb.org/variant/PA166154339

The second record does correctly have a pharmgkb match
https://www.pharmgkb.org/variant/PA166154313

can anyone explain why open-cravat does not identify PA166154339?

**Comment by rkiminsilico** [comment]
Hi, thanks for letting us know. We'll investigate and get back to you.

**Comment by kmoad** [comment]
Hi @cariaso,

We've rebuilt pharmgkb to pick up these variants properly. What was happening was that OC was only recognizing one of the variant-drug associations for that variant.

This change requires a change to what data pharmgkb returns. The new annotator returns two columns. The first is the pharmgkb variant, with a link to the page. The second is a json table containing all the variant-drug associations. There isn't a good way to show this data in the table at the moment, but it's broken out into a table in the widget.

![image](https://user-images.githubusercontent.com/19417207/106714104-5db66b00-65c9-11eb-908c-58a318c62b4d.png)

![image](https://user-images.githubusercontent.com/19417207/106714400-ce5d8780-65c9-11eb-976e-765891801b18.png)

The new annotator/widget use some features of OC that are coming out in the next release (2.2.2). We expect to have that out in the next couple weeks. If you'd like to get early access to it, I can send some instructions for installing dev versions of OC.
