### ISSUE TITLE
Q: Gene View Table

### ISSUE THREAD

**Issue by kokyriakidis** [KarchinLab/open-cravat#45]
Hi!

Is there a way to add a column, on gene view table, with the number of samples (sample_count) that have variants in a particular gene? Right now this information is only available in the variant table, but for each individual variant.

**Comment by kpagel** [comment]
This is a great idea. We will add this to the list of feature requests and will prioritize this addition in the next release or so.

**Comment by kokyriakidis** [comment]
Sample_count + Sample_IDs. 

Also, I am trying to make an analysis on Males vs Females and I have to do custom filtration. It would be wonderful if I can pass a metadata file (ex. Sample\tGender\tCondition) and filter variant and gene tables based on that emtadata file.

**Comment by kpagel** [comment]
There are some aspects of the Filter tab that can be leveraged to quickly filter on a list of samples. In the Samples section,  use the "Sample List" button to select a file that contains the SampleIDs for males (one per line). This process could be repeated for females. 

In the upcoming software update there are also some features designed for Case / Control analyses that may be useful.
