### ISSUE TITLE
cancer_hotspots is not working for hg38?

### ISSUE THREAD

**Issue by naumenko-sa** [KarchinLab/open-cravat#46]
Hello!

Thanks for creating and maintaining open-cravat - such a great annotation tool!

I am annotating with:
```
cravat \
sample.tsv \
-n $bname  \
-a chasmplus chasmplus_BRCA polyphen2 fathmm cosmic cosmic_gene cancer_hotspots \
-d sample_out -l hg38 \
--mp 10 \
-t text
```

and I'm getting all the annotations but cancer_hotspots: it returned NA in all mutations for all samples.
(I have installed the cancer_hotstpots annotator).

I realize that the original database  https://www.cancerhotspots.org/#/home 
is along hg19/b37: https://www.ncbi.nlm.nih.gov/pmc/articles/PMC5808190/,
but I was hoping that open-cravat does the liftover.

Has anybody tacked this issue before?

Thanks!
Sergey

**Comment by rkiminsilico** [comment]
Hi, thanks for letting us know. We'll investigate and get back to you.

**Comment by rkiminsilico** [comment]
Hi, thanks for catching it. We will rebuild the module in hg38 and publish it. When we do so, we'll let you know here.

**Comment by rkiminsilico** [comment]
Hi, we have published a new version of cancer_hotspots which was liftover'd to hg38. Please let us know if it works as it is supposed to.

**Comment by naumenko-sa** [comment]
Thanks, Rick @rkiminsilico !

I've updated cancer_hotspots with:
```
oc module update cancer_hotspots
```
I have also tried:
```
oc module uninstall cancer_hotspots
oc module install cancer_hotspots
```

And reannotated the variants. Cancer_hotspots field is empty.
Could you please double-check?

Sergey

**Comment by naumenko-sa** [comment]
It turned out that my set of variants happened to not having 
any hits with the cancer_hostspots database.

To test, whether it is working you may use a list of mutations having cancer_hostpots annotation:

```
chr16	3738617	+	G	A	s0	v1
chr2	208248388	+	C	T	s1	v2
chr9	21971121	+	G	A	s2	v3
chr4	152330755	+	G	A	s3	v4
chr12	25245350	+	C	A	s4	v5
```
Thanks @kpagel  for resolving this!

**Comment by naumenko-sa** [comment]
Sorry, I'm reopening the issue, since we discovered that 

PIK3CA
grch38: chr3-179,218,303-G-A => grch37: 3:178,936,091-G-A
COSV55873239
https://cancer.sanger.ac.uk/cosmic/mutation/overview?id=169110131&merge=125370
p.E545K

is not annotated by the updated OpenCravat:
the input file:
```
chr3	179218303	+	G	A	S5	vnot_annotated1
```

The mutation is in CancerHotpots (PIK3CA E545):
https://www.cancerhotspots.org/#/home

In the OpenCravat output, CancerHotpots/CancerTypes column for that mutation is empty.

Could you please look into that issue? 
It is possible that we are missing some other CancerHotspot annotations here?
Could you please run the annotation of all mutations in HotSpots as a test?

Thanks!
Sergey

**Comment by mlarsen2** [comment]
Hi Sergey, sorry about these issues with Cancer Hotspots. Some annotations were missing from the previous update, but a new version (1.2.0) has now been published and that annotation, as well as others are now included. 

Thank you so much for your patience!

**Comment by naumenko-sa** [comment]
Thanks, @mlarsen2, PI3K3CA got annotated after the update.

**Comment by naumenko-sa** [comment]
Hello!

Sorry, reopening again.

I have 20 samples carrying the same ESR1 variant:
```
chr6	152098788	+	A	C	sample	var1705
```

It is described in the same way for all 20 samples - same chr, pos, strand, ref, alt.
(Other variants may be different in the samples).

And it is annotated with cancer_hotspots annotation in 18 samples and not annotated (NA) in 2 samples.
All other annotations seem to be working.

The err log file for one of the samples contains an error
```
SOURCE:error.mapper         
LINE:147
INPUT:4372	chr19	58277216	GGGCCAGAAGGATCTGAGAGAGTGTGGCCAGCTTGAGCCCTCAGGAGTC	G
ERROR:name 'SO_UTR3' is not defined
#
```
(it does not break the annotation process).

In the other sample **err** log is empty, but cancer_hotspots annotation is NA.

Could you please clarify, why 2 samples did not get ESR1 variant annotated?
Is it possible that something similar happens with other variants/annotations?

This issue could be critical for the downstream variant prioritization. If some variants are not receiving 
some annotations, they might be filtered out downstream as of mild impact variants, 
i.e. driver mutations could be lost due to annotation error.

Sergey

**Comment by rkiminsilico** [comment]
Hi, sorry about the issue. The error message in the err file means that the hg38 mapper could not properly handle the variant at chr19:58277216. 

I tested the variant myself (since I don't know which assembly it was from, I tested with both `-l hg38` and `-l hg19`), but did not get the error message. Can you try `echo "chr19 58277216 + GGGCCAGAAGGATCTGAGAGAGTGTGGCCAGCTTGAGCCCTCAGGAGTC G"|oc run - --skip annotator -t text -l hg19 --input-format cravat` and see if the err file `cravat_run.err` has the same error?

Also, the latest oc and hg38 versions are oc 2.2.0 and hg38 1.9.9. Can you let me know which versions you get with `oc version` and `oc module ls hg38` ?

**Comment by naumenko-sa** [comment]
Hi @rkiminsilico !

Thanks for following up! 
It was rather an R parsing error: in some samples `Cancer Types` column was read as logical 
in R and it failed to parse  the row with ESR1 mutation 
```R
variants <- read_tsv(args[1], skip = 1, col_types = cols(`Cancer Types` = col_character()))) %>% 
    dplyr::select(Chrom, Position, `Ref Base`, `Alt Base`, Coding, Gene,
                  `Sequence Ontology`, `cDNA change`, `Protein Change`,
                  `P-value`, `P-value_1`,
                  `Score_2`, `Prediction`,
                  `HVAR Raw Score`, `HVAR Prediction`, ID, `Cancer Types`)
```
specifying `col_types = cols(`Cancer Types` = col_character())` helps to parse it correctly.

I posted the full log below, 
as it might be helpful to somebody in the future.

Also, I see a new error with CHASMPlus - could you please comment on that?

I'm annotating against hg38 (see my first post for a script).

Test1:
```
echo "chr19 58277216 + GGGCCAGAAGGATCTGAGAGAGTGTGGCCAGCTTGAGCCCTCAGGAGTC G"|oc run - --skip annotator -t text -l hg19 --input-format cravat
```
output
```
Input file(s): stdin
Genome assembly: hg19
Running converter...
	Converter (converter)         	finished in 1.797s
Running gene mapper...                  finished in 3.478s
Running aggregator...
	Variants                      	finished in 0.183s
	Genes                         	finished in 0.153s
	Samples                       	finished in 0.171s
	Tags                          	finished in 0.344s
Indexing
	variant base__coding	finished in 0.001s
	variant base__chrom	finished in 0.000s
	variant base__so	finished in 0.000s
Running postaggregators...
	Tag Sampler (tagsampler)      	finished in 0.136s
	VCF Info (vcfinfo)            	finished in 0.011s
	Variant Metadata (varmeta)    	finished in 0.017s
Running reporter...
	Text Reporter (textreporter)  	finished in 0.359s
Finished normally. Runtime: 6.959s
```

I have also tried hg38 - same result - no errors.

Test2.
```
$ oc version
2.1.0
$ oc module ls hg38
Name    Title                    Type      Version    Data source ver    Size        
hg38    UCSC hg38 Gene Mapper    mapper    1.9.6                         353.1 MB  
```
I see - maybe these modules are out of date - I updated only cancer_hotspots.

I updated them:
```
$ pip install open-cravat --upgrade --no-cache-dir
# here I had to deactivate and re-activate my conda environment to get it running
$ oc version
2.2.1
$ oc module ls -a
# installed modules are gone - erased by the update?
$ oc module install-base
$ oc module install chasmplus chasmplus_BRCA polyphen2 fathmm cosmic cosmic_gene cancer_hotspots
oc module ls hg38
Name  Title                  Type    Version  Data source ver  Size      
hg38  UCSC hg38 Gene Mapper  mapper  1.9.9                     353.2 MB  
```

Annotated the first sample (which had SO_UTR3 error):
No error this time, cancer_hotstpots annotation is present, 
and a new error in the log:
```
2020/12/23 12:41:38 cravat               no such column: chasmplus__chasmplus_BRCA__pval
Traceback (most recent call last):
  File "lib/python3.8/site-packages/cravat/cravat_class.py", line 1321, in run_reporter
    response_t = await reporter.run()
  File "lib/python3.8/site-packages/cravat/cravat_report.py", line 452, in run
    await self.run_level(level)
  File "lib/python3.8/site-packages/cravat/cravat_report.py", line 302, in run_level
    gene_summary_data = await o.get_gene_summary_data(self.cf)
  File "lib/python3.8/site-packages/cravat/base_annotator.py", line 287, in get_gene_summary_data
    rows = await cf.exec_db(cf.get_variant_data_for_cols, cols)
  File "lib/python3.8/site-packages/cravat/cravat_filter.py", line 196, in exec_db
    ret = await func(*args, conn=conn, cursor=cursor, **kwargs)
  File "lib/python3.8/site-packages/cravat/cravat_filter.py", line 726, in get_variant_data_for_cols
    await cursor.execute(q)
  File "lib/python3.8/site-packages/aiosqlite/cursor.py", line 36, in execute
    await self._execute(self._cursor.execute, sql, parameters)
  File "lib/python3.8/site-packages/aiosqlite/cursor.py", line 30, in _execute
    return await self._conn._execute(fn, *args, **kwargs)
  File "lib/python3.8/site-packages/aiosqlite/core.py", line 109, in _execute
    return await future
  File "lib/python3.8/asyncio/futures.py", line 260, in __await__
    yield self  # This tells Task to wait for completion.
  File "lib/python3.8/asyncio/tasks.py", line 349, in __wakeup
    future.result()
  File "lib/python3.8/asyncio/futures.py", line 178, in result
    raise self._exception
  File "lib/python3.8/site-packages/aiosqlite/core.py", line 95, in run
    result = function()
sqlite3.OperationalError: no such column: chasmplus__chasmplus_BRCA__pval
2020/12/23 12:41:38 cravat               finished with an exception: Wed Dec 23 12:41:38 2020
2020/12/23 12:41:38 cravat               runtime: 11.508s
```

Annotating the second sample (which had no error but no ESR1 cancer_hotspots annotation) - 
same result.

Thanks!
Sergey

**Comment by naumenko-sa** [comment]
upd: I reinstalled the module - it did not help

```
oc module uninstall chasmplus_BRCA
oc module install chasmplus_BRCA
```

**Comment by rkiminsilico** [comment]
Thanks for letting us know. 

Although it seems that you have just updated hg38, if hg38 still does not give annotation, please do `oc module update hg38` to get v1.9.10 (should be the same content but just to make sure you get the latest).

To diagnose chasmplus_BRCA, please do `oc util test -m chasmplus_BRCA` and let me know if it passes.

If you use R to analyze further, tsvreporter or rdatareporter would be easier to work with than textreporter. I could do the following, for example.
```
oc module install rdatareporter
oc run input -a chasmplus_BRCA -t rdatareporter
R
>data<-get(load('input.variant.RData'))
```
or
```
oc module install tsvreporter
oc run input -a chasmplus_BRCA -t tsvreporter
R
>data<-readf_tsv('input.variant.tsv')
```

**Comment by naumenko-sa** [comment]
Thanks for the hint with tsvreporter!

After the hg38 update, the chasmplus_BRCA error is gone.
`oc util test -m chasmplus_BRCA` all passed.

Closing.
SN
