### ISSUE TITLE
docker multiuser

### ISSUE THREAD

**Issue by volyavi** [KarchinLab/open-cravat#49]
Hello,

Thank you for this great tool.
I installed openCravat on my linux server and it run well.

But I have issue to run multiuser mode.
I installed opencravat and open-cravat-multiuser with pip/conda/docker but it is the same issue.
When I ran `oc gui --multiuser ` the openCravat web page (0.0.0.0:8080) isn't avaible. 

For example for docker installation:

I followed  [docker hub](https://hub.docker.com/r/karchinlab/cravatmupit) instruction for linux:

In the docker-compose.yml I changed this :     `command: ['oc', 'gui'] ` to  ` command: ['oc', 'gui' ,  '--multiuser' ]` for run multiuser mode.

But when I run the docker with : `docker-compose up -d ` 
the web page (0.0.0.0:8080) it'not avaible.

So I was woddering if I did somthing wrong?
Or if I have to first  setup  in particular  way my server before make the openCravat installation?

Thank you again. 

Ivaylo

**Comment by kmoad** [comment]
Hi volyavi,

We've been able to recreate this issue and are working to diagnose and fix it. I'll let you know here when we know more.

**Comment by kmoad** [comment]
There was an issue with a separate package we have that does some of the multiuser functionality. It should be fixed now. Repull the container with either 2.1.2 or latest tag and try again. Also, if you're using a mounted volume for `/mnt/conf` you'll need to delete `admin.sqlite*` from that directory before rerunning.

**Comment by kmoad** [comment]
The fix is also available through pip installed OpenCRAVAT if you upgrade the `open-cravat-multiuser` python package to version `2.2.0`.

```
pip3 install --upgrade open-cravat-multiuser
```

**Comment by volyavi** [comment]
Hi kmoad,

It works now.
I ran openCravat  with docker and as you sayed to repull again and to delet admin.sqlite* file.

Thank you!
