### ISSUE TITLE
How do I test whether individual annotators are working?

### ISSUE THREAD

**Issue by DCGenomics** [KarchinLab/open-cravat#5]

**Comment by kmoad** [comment]
Hi Ben, thanks for the question. There's a testing tool integrated with open-cravat. Annotator developers are encouraged to include a set of test inputs, and an answer key with their modules. You can run a test with `cravat-test -m <annotator_name>`. It will run open-cravat against their test input, and report if the output of the text report matches their key. The results will be put in a subdirectory of your working dir, called something like `cravat_test_1537282126162`.
