### ISSUE TITLE
Save filter and annotat vcf + sqlite 

### ISSUE THREAD

**Issue by volyavi** [KarchinLab/open-cravat#51]
Hi,

It that possible to annotate a vcf and a sqlite file at the same time? 

I would like to filter variants on some criteria. So I use openCravat filter and save it but I would like to use this filter for other analysis. Is that possible? Same question about the layout ( colones order in web interface). 

Thank you again

Ivaylo

**Comment by rkiminsilico** [comment]
Hi, this coming release of OpenCRAVAT will have export/import feature for filters. Thus, for example, you will be able to do the following.

>oc run input.vcf ...
>oc gui input.sqlite

You can create a filter and save it, then export it to a json file such as filter.json. Then,

>oc gui input2.vcf -f filter.json -t vcf

This will produce input2.vcf.vcf with the filtered variants from the variants in input2.vcf.

Was this what you were asking about?

**Comment by volyavi** [comment]
Thank you,this (filter export) will be great.

also I would like to mixe vcf and sqlite annotation like this:

```
oc run input.vcf input2.sqlite 
```
The main idea is to keep previous annotation with personal notes ( on some variant) in input2.sqlite and to append the new variants with the oc annotation tools.

I try to do this but it did not work. May be I did on the wrong way ?

**Comment by rkiminsilico** [comment]
Mixing text files and sqlite files as input to `oc run` is currently not supported, but that is an interesting use case. We'll get back to you here with possible solutions.
