### ISSUE TITLE
NoneType error when running cravat

### ISSUE THREAD

**Issue by YangShi-PKU** [KarchinLab/open-cravat#52]
Hi,
Thanks for developing such an awesome tool! I want to use it to calculate pathogenic score of mutations, however, when I run this command using example input file, there is an error, seems related with multiprocessing:
`2020/12/03 15:02:33 cravat               /home/shiyang/softwares/anaconda3/envs/chasmplus/bin/cravat -n MYRUN -t excel -a chasmplus -d /home/shiyang/Project/A317_001/ccf/cravat_result/ -l hg19 --mp 1 /home/shiyang/Project/A317_001/ccf/input.txt
2020/12/03 15:02:33 cravat               started: Thu Dec  3 15:02:33 2020
2020/12/03 15:02:33 cravat               conf file: None
2020/12/03 15:02:33 cravat               input files: /home/shiyang/Project/A317_001/ccf/input.txt
2020/12/03 15:02:33 cravat               input assembly: hg19
2020/12/03 15:02:33 cravat.converter     started: Thu Dec  3 15:02:33 2020
2020/12/03 15:02:33 cravat.converter     Input file(s): /home/shiyang/Project/A317_001/ccf/input.txt
2020/12/03 15:02:33 cravat.converter     liftover from hg19
2020/12/03 15:02:34 cravat.converter     input format: cravat
2020/12/03 15:02:34 cravat.converter     error lines: 0
2020/12/03 15:02:34 cravat.converter     finished: Thu Dec  3 15:02:34 2020
2020/12/03 15:02:34 cravat.converter     num input lines: 100
2020/12/03 15:02:34 cravat.converter     runtime: 0.005
2020/12/03 15:02:34 cravat               input line chunksize=1 total number of input lines=100 number of chunks=95
2020/12/03 15:02:34 cravat               An unexpected exception occurred.
multiprocessing.pool.RemoteTraceback:
"""
Traceback (most recent call last):
  File "/home/shiyang/softwares/anaconda3/envs/chasmplus/lib/python3.7/multiprocessing/pool.py", line 121, in worker
    result = (True, func(*args, **kwds))
  File "/home/shiyang/softwares/anaconda3/envs/chasmplus/lib/python3.7/site-packages/cravat/mp_runners.py", line 32, in mapper_runner
    kwargs = {'script_path': module.script_path, 'input_file': crv_path, 'run_name': run_name, 'seekpos': seekpos, 'chunksize': chunksize, 'slavemode': True, 'postfix': f'.{pos_no:010.0f}', 'output_dir': output_dir}
AttributeError: 'NoneType' object has no attribute 'script_path'
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/shiyang/softwares/anaconda3/envs/chasmplus/lib/python3.7/site-packages/cravat/cravat_class.py", line 425, in main
    self.run_genemapper_mp()
  File "/home/shiyang/softwares/anaconda3/envs/chasmplus/lib/python3.7/site-packages/cravat/cravat_class.py", line 998, in run_genemapper_mp
    job.get()
  File "/home/shiyang/softwares/anaconda3/envs/chasmplus/lib/python3.7/multiprocessing/pool.py", line 657, in get
    raise self._value
AttributeError: 'NoneType' object has no attribute 'script_path'
2020/12/03 15:02:34 cravat               finished with an exception: Thu Dec  3 15:02:34 2020
2020/12/03 15:02:34 cravat               runtime: 1.194s`

Could you help me on this?
I run it on a linux system, my python version is 3.7 and I installed cravat using pip.

Thanks

Yang

**Comment by rkiminsilico** [comment]
Hi, thanks for using OpenCRAVAT. For diagnosis, can you let me know what you get with the command `oc module ls` ?

**Comment by YangShi-PKU** [comment]
Hi, these are the modules I've installed. Thanks!
![image](https://user-images.githubusercontent.com/28683548/101310923-20648400-388b-11eb-83e8-51507b0f2e6f.png)

**Comment by rkiminsilico** [comment]
Thanks. It seems that system modules of OpenCRAVAT are not installed. Please do `oc module install-base` to install them and run the job again. Let me know if this resolves the issue.

**Comment by YangShi-PKU** [comment]
It solves my problem perfectly, thank you very much!
