### ISSUE TITLE
ClinGen Allele Registry ids?

### ISSUE THREAD

**Issue by cariaso** [KarchinLab/open-cravat#55]
Is there any way that open-cravat is able to provide the IDs from
http://reg.clinicalgenome.org/redmine/projects/registry/genboree_registry/landing
such as 
CA123770
shown at 
http://reg.clinicalgenome.org/redmine/projects/registry/genboree_registry/by_caid?caid=CA123770

I've not yet seen a downloadable file for offline use, so I suspect not.

**Comment by rkiminsilico** [comment]
Hi, sure we'll take a look and get back to you.

**Comment by cariaso** [comment]
I just noticed that 
http://reg.clinicalgenome.org/doc/AlleleRegistry_1.01.xx_api_v1.pdf
mentions a
"Bulk query of alleles with VCF file"
which seems to eliminate the need for an HGVS conversion which currently seems difficult via open-cravat, due to lack of exposed reference name.

Perhaps of use.

**Comment by kmoad** [comment]
Sorry for the late response. We have put a clingen allele registry annotator into the queue.
