### ISSUE TITLE
missing python module 'vcf'

### ISSUE THREAD

**Issue by loipf** [KarchinLab/open-cravat#56]
Hi all,

just wanted to tell you that there the python library `pyvcf` was missing for me when I used bioconda to install open-cravat.
running the main function I got an error that the missing python module `vcf` could not be installed. 
sorry I do not have any reproducible example or report. a simple installation of `pyvcf` fixed everything and it worked.
nothing urgent or anything, just to let you know. nice software !

Dockerfile:
```
FROM conda/miniconda3

RUN apt-get update

RUN conda config --add channels defaults
RUN conda config --add channels bioconda
RUN conda config --add channels conda-forge

RUN conda install \
		pyvcf==0.6.8 \
		open-cravat==2.2.1

### set up open-cravat
RUN oc module install -y csvreporter vcfreporter 
RUN oc module install -y clinvar 
```

**Comment by rkiminsilico** [comment]
Thanks for letting us know. We'll update the recipe and let you know here.

**Comment by rkiminsilico** [comment]
@loipf Bioconda recipe for open-cravat has been updated with pyvcf dependency.
