### ISSUE TITLE
check that reqired annotators installed (in .yml) fails

### ISSUE THREAD

**Issue by EugeneEA** [KarchinLab/open-cravat#59]
Hi, I have a custom annotator which, relyes on multiple of other annotators, everything works fine (thanks a lot!), but there is an issue with dependancies. 

According to manual (https://open-cravat.readthedocs.io/en/latest/Annotator-Reference.html)
I'm inserting necessary rows in yml file:

```
requires:
- clinvar
- ...etc
```

but even if I'm listing there missing (or non existing) annotators everything works perfectly (offcourse untill I actlually try to fetch missing data with `secondary_inputs:`).
Am I doing something wrong or this functionality does not work?
PS later I also like to specify versions of the annotators (to avoid these issues https://github.com/KarchinLab/open-cravat/issues/48). I'm fin if oc would just crashes of the version is incorrect, the real annotator-verson control is probably different stroy. 

Best, Eugene

**Comment by rkiminsilico** [comment]
Hi Eugene,

When you develop a module inside the modules directory, `requires` is not used for the module's functionality. When the module is published and installed with `oc module install`, then the modules defined in `requires` will be installed also. If a non-existing module is defined under `requires`, that wrong module will be ignored in the installation.

**Comment by EugeneEA** [comment]
Ok, thanks for the clarification! 
Best, Eugene
