### ISSUE TITLE
cravat.exceptions.BadFormatError: All sample GT are zero

### ISSUE THREAD

**Issue by antonkulaga** [KarchinLab/open-cravat#61]
I am constantly getting "All sample GT are zero" error. And it is true for vcf-s produced by 3 different variant callers (strelka, deepvariant, smove). Any ideas what can be the reason for it? I had not issues when annotating same vcf-s with VEP
```
 File "/usr/local/lib/python3.6/site-packages/cravat/cravat_convert.py", line 375, in run
    all_wdicts = converter.convert_line(l)
  File "/usr/local/lib/python3.6/site-packages/cravat/modules/converters/vcf-converter/vcf-converter.py", line 191, in convert_line
    raise BadFormatError('All sample GT are zero')
cravat.exceptions.BadFormatError: All sample GT are zero
```
Here is Deepvariant vcf http://agingkills.eu:8001/data/gwas/anton//variants//deepvariant/ and here is strelka ones http://agingkills.eu:8001/data/gwas/anton//OLD//variants//strelka_run//results//variants/ All aligned to hg38-based Ensembl 102 genome
The pipeline is https://github.com/antonkulaga/dna-seq

**Comment by rkimoakbioinformatics** [comment]
Thanks for letting us know. The message means that a sample did not have any variant for a position different from the position's reference base. A file ending with `.err` should have been produced, which lists all such positions.

Thus, the message was not really an error in that something went wrong. I agree that the message can be misleading. We'll improve the message in the next version.
