### ISSUE TITLE
provide option to download everything on the website

### ISSUE THREAD

**Issue by antonkulaga** [KarchinLab/open-cravat#62]
I constantly get "The OpenCRAVAT viewer cannot display more than 100000 variants." in the same time there are no download buttons to download annotations in some format (for instance gziped tsv), it would be nice to have one, so users will be able to download annotation files to analyze them programmatically.

**Comment by rkimoakbioinformatics** [comment]
Hi, can you let me know about the following?

1. How was your OpenCRAVAT installed?
1.1 No installation. Just using run.opencravat.org
1.2 with `pip`. In this case, Do you open the result viewer with directly `oc gui xxxxx.sqlite` or first `oc gui` and then "Result Viewer" button on the job list?
1.3 with a Windows or Mac installer
