### ISSUE TITLE
Mutect2 Gatk4 VCFs not accepted

### ISSUE THREAD

**Issue by mmterpstra** [KarchinLab/open-cravat#66]
Hi cravat team,

The 'POPAF' tag produces infinite values in Mutect2(gatk4) output and your program crashes on it. Maybe close/wontfix it for now. This is mainly to point other users in the right direction. Below an typed/ not tested example vcf displaying the infinity value. 

This triggers a jsondecode error

Example vcf:

```
##fileformat=VCFv4.2
##GATKCommandLine=<ID=Mutect2,CommandLine="Mutect2  --tumor-sample sample1 --panel-of-normals /path/to/merge_excluding_sample1.vcf.gz --germline-resource /apps/data/gnomAD/release-170228/vcf/exomes/gnomad.exomes.r2.0.2.sites.normalized.vcf.gz --af-of-alleles-not-in-resource 2.5E-6 --bam-output /path/to/sample1.bam --output /path/to/sample1.vcf.gz --intervals /path/to/human_g1k_v37/WES_captured.interval_list --input originalbams/sample1.bam --reference /path/to/human_g1k_v37.fasta --disable-read-filter MateOnSameContigOrNoMappedMateReadFilter  --f1r2-median-mq 50 --f1r2-min-bq 20 --f1r2-max-depth 200 --genotype-pon-sites false --genotype-germline-sites false --mitochondria-mode false --tumor-lod-to-emit 3.0 --initial-tumor-lod 2.0 --pcr-snv-qual 40 --pcr-indel-qual 40 --max-population-af 0.01 --downsampling-stride 1 --callable-depth 10 --max-suspicious-reads-per-alignment-start 0 --normal-lod 2.2 --ignore-itr-artifacts false --gvcf-lod-band -2.5 --gvcf-lod-band -2.0 --gvcf-lod-band -1.5 --gvcf-lod-band -1.0 --gvcf-lod-band -0.5 --gvcf-lod-band 0.0 --gvcf-lod-band 0.5 --gvcf-lod-band 1.0 --minimum-allele-fraction 0.0 --independent-mates false --disable-adaptive-pruning false --dont-trim-active-regions false --max-extension 25 --padding-around-indels 150 --padding-around-snps 20 --kmer-size 10 --kmer-size 25 --dont-increase-kmer-sizes-for-cycles false --allow-non-unique-kmers-in-ref false --num-pruning-samples 1 --min-dangling-branch-length 4 --recover-all-dangling-branches false --max-num-haplotypes-in-population 128 --min-pruning 2 --adaptive-pruning-initial-error-rate 0.001 --pruning-lod-threshold 2.302585092994046 --max-unpruned-variants 100 --linked-de-bruijn-graph false --debug-assembly false --debug-graph-transformations false --capture-assembly-failure-bam false --error-correct-reads false --kmer-length-for-read-error-correction 25 --min-observations-for-kmer-to-be-solid 20 --likelihood-calculation-engine PairHMM --base-quality-score-threshold 18 --pair-hmm-gap-continuation-penalty 10 --pair-hmm-implementation FASTEST_AVAILABLE --pcr-indel-model CONSERVATIVE --phred-scaled-global-read-mismapping-rate 45 --native-pair-hmm-threads 4 --native-pair-hmm-use-double-precision false --bam-writer-type CALLED_HAPLOTYPES --dont-use-soft-clipped-bases false --min-base-quality-score 10 --smith-waterman JAVA --emit-ref-confidence NONE --max-mnp-distance 1 --force-call-filtered-alleles false --min-assembly-region-size 50 --max-assembly-region-size 300 --assembly-region-padding 100 --max-reads-per-alignment-start 50 --active-probability-threshold 0.002 --max-prob-propagation-distance 50 --force-active false --interval-set-rule UNION --interval-padding 0 --interval-exclusion-padding 0 --interval-merging-rule ALL --read-validation-stringency SILENT --seconds-between-progress-updates 10.0 --disable-sequence-dictionary-validation false --create-output-bam-index true --create-output-bam-md5 false --create-output-variant-index true --create-output-variant-md5 false --lenient false --add-output-sam-program-record true --add-output-vcf-command-line true --cloud-prefetch-buffer 40 --cloud-index-prefetch-buffer -1 --disable-bam-index-caching false --sites-only-vcf-output false --help false --version false --showHidden false --verbosity INFO --QUIET false --use-jdk-deflater false --use-jdk-inflater false --gcs-max-retries 20 --gcs-project-for-requester-pays  --disable-tool-default-read-filters false --max-read-length 2147483647 --min-read-length 30 --minimum-mapping-quality 20 --disable-tool-default-annotations false --enable-all-annotations false",Version="4.1.4.1",Date="March 27, 2021 5:14:43 PM UTC">
##INFO=<ID=POPAF,Number=A,Type=Float,Description="negative log 10 population allele frequencies of alt alleles">
#CHROM	POS	ID	REF	ALT	QUAL	FILTER	INFO	FORMAT	sample1
1	100	.	N	G	.	.	POPAF=5.60	GT:AD	1/1:0,100
1	100	.	N	G	.	.	POPAF=Infinity	GT:AD	1/1:0,100
```

ugly fix:

```
zcat $i|perl -wpe ' s/Infinity/999/g if(not(m/^#/));' | bgzip > $(dirname $i)/$(basename $i .vcf.gz).inffix.vcf.gz
```

**Comment by rkimoakbioinformatics** [comment]
@mmterpstra Thanks for the information. How do you use `Infinity` value in your work downstream? If a sensible replacement value or behavior for `Infinity` exists, OpenCRAVAT VCF converter can adopt that. I see that it is replaced with `999` in your fix. Is it used somehow later? If not, off the top of my head, how about dropping `Infinity` when a field is supposed to be a number, for example `POPAF=Infinity` will be dropped in OpenCRAVAT output?

**Comment by mmterpstra** [comment]
Probably in population filtering maybe 99 as a max would also suffice because a population af of <7.8*10^-9 would need more then the entire earth population to be sequenced (in this case). 

Can' t say for every use case the '99' solution would be an acceptable value because 10^-99 is way smaller then 7.8*10^-9.

btw:
Maybe a warning dumping the values for the variable around: https://github.com/KarchinLab/open-cravat/blob/cfcb2ab67040259bf50b393b86e6808d77638f50/cravat/inout.py#L168

I'm using opencravat version 1.8.0 so this might not affect current version (this might skip the token/field).

**Comment by mmterpstra** [comment]
Reproduction of the error:  

```
File "/apps/software/open-cravat/1.8.0-foss-2018b-Python-3.6.6/lib/python3.6/site-packages/cravat/inout.py", line 156, in loop_data
    tok = json.loads(tok)
  File "/apps/software/Python/3.6.6-foss-2018b/lib/python3.6/json/__init__.py", line 354, in loads
    return _default_decoder.decode(s)
  File "/apps/software/Python/3.6.6-foss-2018b/lib/python3.6/json/decoder.py", line 339, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/apps/software/Python/3.6.6-foss-2018b/lib/python3.6/json/decoder.py", line 357, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

```

**Comment by rkimoakbioinformatics** [comment]
@mmterpstra Yes, with the latest versions, OpenCRAVAT 2.2.3 and vcf-converter module 2.0.3, the default behavior is that `Infinity` values are just dropped without an error.

However, I noticed that your example input has `N` as the reference base. Currently, OpenCRAVAT will set them aside as variants with invalid reference bases. I wonder if `N` was the output from pipeline and thus would need consideration or if it was just an arbitrary example. Can you let me know?

**Comment by mmterpstra** [comment]
arbitrary example

**Comment by rkimoakbioinformatics** [comment]
@mmterpstra Ok. Thanks for letting me know. Regarding `Infinity`, it may be possible to implement something like

`oc run input.vcf --module-option vcd-converter.replace_info_value=POPAF:Infinity:99`

so that `Infinity` in `POPAF` field will be replaced with `99` before further analysis. Does this syntax look sensible to you? Or, would there be another way that feels more natural to you?

**Comment by rkimoakbioinformatics** [comment]
@mmterpstra By the way, we are conducting interviews to learn what else OpenCRAVAT could do for researchers who use variant analysis. Given the helpful input you already provided, would you to have a 15 minutes chat with me? It will take just about 15 minutes and your input will be invaluable to make OpenCRAVAT even better. It does not have to be about your experience with OpenCRAVAT. We just would like to hear what your experience has been with genomic variant analysis tools.

**Comment by mmterpstra** [comment]
I'm a bit meeh on continue on using opencravat on my dataset due to being hg19 and being picky for example I'm also annotating freebayes data with out allelic prios and this will spit out 0/0 genotypes these are omitted by opencravat 1.8.0 (maybe include err field in opencravat's output vcf/other formats so that `vcf in == vcf out` at least in amount of records). Now I'm using snpEff(https://github.com/pcingola/SnpEff) and vcfanno (https://github.com/brentp/vcfanno) with the correct databases. Also consider runnning annotations on known clinical/tumor databases like clinvar/TCGA to see how many are/aren't detectable.

**Comment by rkimoakbioinformatics** [comment]
@mmterpstra Thanks for the valuable input. We'll improve OpenCRAVAT based upon it. 

I'd still like to ask you if you would be willing to give a quick interview. What I would like to know is more general aspects of how variant annotation is used by researchers like you. By knowing how it is being done, it would eventually help making OpenCRAVAT better. Would you be willing to?
