### ISSUE TITLE
genebass data source

### ISSUE THREAD

**Issue by cariaso** [KarchinLab/open-cravat#68]
https://genebass.org/
seems like a worthy annotation source with a permissive license
https://genebass.org/terms
and bulk download available from
https://genebass.org/downloads

example results
https://genebass.org/gene/ENSG00000130203?burdenSet=pLoF&phewasOpts=1&resultLayout=full

**Comment by rkimoakbioinformatics** [comment]
Thanks. We'll take a look.

**Comment by kmoad** [comment]
Currently this database is too large to include in OpenCRAVAT. We are working on ways to either better compress annotator data, or support fast querying of external resources. Genebass does seem like an excellent data source.
