### ISSUE TITLE
Lack of correspondence between sample names and sample info in multisample VCF annotation results

### ISSUE THREAD

**Issue by EugeneEA** [KarchinLab/open-cravat#69]
Hi, I've noticed a possible bug in annotation of multisample vcf files.
I have several sample names in subcolum  "Sample" of the column set "Variant annotation". I expect the order of names in that column correspond to order of mraks in subcolumn "Zygocity" of column set "Vcf info". But currentl y it seems that order is random. (at least I can see mistakes, exploring individual files for zygocity info). Cravat version 2.2.3

Best, Eugene

**Comment by rkimoakbioinformatics** [comment]
Hi Eugene, 

Thanks for letting us know. We'll take a look into it.

Rick

**Comment by rkimoakbioinformatics** [comment]
@EugeneEA I tested with OpenCRAVAT 2.2.5 and a vcf file, and the order seems correct. Can you check with OpenCRAVAT 2.2.5? If you can give me (rkim@oakbioinformatics.com) the input file with which you saw the problem, I can test it myself, too.

**Comment by EugeneEA** [comment]
Hi Rick, sorry for the late reply, I've sent you the vcf (albert.ea@phystech.edu)

Best, Eugene

**Comment by rkimoakbioinformatics** [comment]
Hi Eugene, thanks, but I have not received the email yet. Maybe somehow it was lost? Can you send me again?

**Comment by EugeneEA** [comment]
Have sent you another one from different mail box, check your spam folder, just in case)

**Comment by rkimoakbioinformatics** [comment]
@EugeneEA Thanks. Indeed there was a bug in tagsampler module - it was sorting sample names, which caused the inconsistency between the order of samples and that of sample-specific values. Fixed tagsampler has been published as version 1.1.5. Please check this version if this works for you.

**Comment by rkimoakbioinformatics** [comment]
Just in case, you can update tagsampler by `oc module update tagsampler` or `oc module install -f tagsampler`.

**Comment by EugeneEA** [comment]
Ok, thanks for looking into this! Some thought for improvements then: I'm for example a bit reluctant to update annotators too often due to possible backwards compatibility issues for the results. Therefore I do not use "update all" button in store, and therefore I did not get the fixed tagsampler when it was out. So may be it make sense to split updates into data (annotator) updates and code updates.

**Comment by EugeneEA** [comment]
> @EugeneEA Thanks for your suggestion, which makes sense. Would something like `oc module update --same-data-version-only` make sense, to update only the modules which has the same data version as installed?

Yes, I think it's a valuable option
