### ISSUE TITLE
How best handle missing dependencies or incompatible versions of already installed packages? 

### ISSUE THREAD

**Issue by RachelKarchin** [KarchinLab/open-cravat#7]
Example:  distributed 1.22.0 requires msgpack, which is not installed.
tensorboard 1.8.0 has requirement bleach==1.5.0, but you'll have bleach 2.1.3 which is incompatible.
tensorboard 1.8.0 has requirement html5lib==0.9999999, but you'll have html5lib 1.0.1 which is incompatible.

**Comment by rkiminsilico** [comment]
Module dependencies are handled by the latest open-cravat now.
