### ISSUE TITLE
OpenCravat hangs on dbsnp_common

### ISSUE THREAD

**Issue by duartemolha** [KarchinLab/open-cravat#70]
I noticed whilst running my sample that open-cravat hangs in the dbsnp_common... I went to the terminal windows and pressed return and it continued with no problem.

Is this something reported before?

**Comment by rkimoakbioinformatics** [comment]
Thanks for letting us know. We'll take a look and get back to you.

**Comment by rkimoakbioinformatics** [comment]
@duartemolha I tested with OC's example input fille and dbsnp_common, and did not see the problem. Maybe it is variant-specific. Can you share with me, by any chance, the input file you were using when you noticed the problem? My email is rkim@oakbioinformatics.com.

**Comment by duartemolha** [comment]
Unfortunately I cannot share those files with you

But it could be related to the size of them. I was running 2 vcf files
containing all the WGS variants (SNP and INDELS, respectively)  of 4
individuals.

Besides being very large files ... They are private data that I cannot
share with you

**Comment by rkimoakbioinformatics** [comment]
@duartemolha No problem. Can you let me know about the following?

- Operating system
- Were you using "oc run" command or "oc gui" and submitting a job through the GUI?
- What is the version of OpenCRAVAT you were using?
