### ISSUE TITLE
can 'oc report ' output an annotated VCF?

### ISSUE THREAD

**Issue by jlac** [KarchinLab/open-cravat#71]
On the documentation page (https://open-cravat.readthedocs.io/en/latest/2.-Command-line-usage.html#report-generate-a-report-from-a-job ) it lists 'vcf' as an output format, but this is not available with the latest version when I try to run it. Outputting an annotated VCF is an important feature to allow downstream further filtering and analysis (e.g., burden tests, etc.). Can you clarify how to output an annotated VCF? Thank you.

**Comment by rkimoakbioinformatics** [comment]
Hi, the module for generating VCF format output files is vcfreporter, which is normally installed when open-cravat is installed. If it is not in your system somehow, you can install it with

>oc module install vcfreporter

Then, "-t vcf" option will work with "oc run" and "oc report".

By the way, what is the version of open-cravat in your system? "oc version" will show the version.

**Comment by jlac** [comment]
Thank you for the quick answer! That did indeed fix the issue. And I am running version 2.2.5
