### ISSUE TITLE
Display more than 100,000 variants

### ISSUE THREAD

**Issue by kokyriakidis** [KarchinLab/open-cravat#74]
Hi!

Is there a way to display more than 100,000 variants in the oc gui? I want to do some column filtering etc and then export it.

**Comment by rkimoakbioinformatics** [comment]
Hi @kokyriakidis, sorry for this late reply. There is a way to change the setting, but we observed performance issues on the browser side with more variants. Please see the following to experiment with the setting.

>ocdir=`oc config system|grep package|cut -f2 -d' '`

Open the file $ocdir/webresult/nocache/js/variables.js.

NUMVAR_LIMIT is the limit of the number of variants for the result browser. Change it to a desired value and save. Then, the next time `oc gui` is run, this new limit will be applied.

By the way, how many variants do you need to load on the result viewer?
