### ISSUE TITLE
[original_input] module does not exist in the system.

### ISSUE THREAD

**Issue by AshirBorah** [KarchinLab/open-cravat#75]
I am using the terminal to annotate a VCF file using hg19. The command I am using is:
`oc run file1.vcf -l hg19 -d oc_run -t csv tsv pandas`

The annotations seem to run fine but I get the following errors when the reporters start. I am not sure what module oc is actually missing. These reporters show up when I try to list all the reporters

Thank you for making this great tool. It has been incredibly helpful.

```
Running reporter...
	CSV Reporter (csvreporter)    	            [original_input] module does not exist in the system. Gene level summary for this module is skipped.
report created: /home/aborah/Mutect2_VCF/oc_run/file1.vcf.variant.csv finished in 4.013s
	TSV Reporter (tsvreporter)    	            [original_input] module does not exist in the system. Gene level summary for this module is skipped.
report created: /home/aborah/Mutect2_VCF/oc_run/file1.vcf.variant.tsv finished in 4.002s
	pandas Reporter (pandasreporter)	            [original_input] module does not exist in the system. Gene level summary for this module is skipped.
```

**Comment by rkimoakbioinformatics** [comment]
@AshirBorah `[original_input] module does not exist in the system. Gene level summary for this module is skipped` is just an artifact and can be safely ignored, so please disregard the message. We'll remove that message in the next release of OpenCRAVAT.

**Comment by rkimoakbioinformatics** [comment]
And, we are glad that you find OpenCRAVAT useful. If you have some need you wish OpenCRAVAT fulfilled, please feel free to let us know here or support@cravat.us.
