### ISSUE TITLE
OncoKB

### ISSUE THREAD

**Issue by katelynmullen** [KarchinLab/open-cravat#81]
Do you guys have plans to add OncoKB to the opencravat store? I am a curator for this database, so I may be a little bit biased, but I think it would be a useful annotator to include! Thanks!

**Comment by rkimoakbioinformatics** [comment]
We are developing an OncoKB OpenCRAVAT module in collaboration with OncoKB. Closing this thread for now.

**Comment by haochenz96** [comment]
I see OncoKB posted to the annotator store, but I don't think it is deployed on the server?

**Comment by rkimoakbioinformatics** [comment]
@haochenz96 Thanks for catching it. It's now installed on the server.

**Comment by haochenz96** [comment]
Hi Rick- it seems that OncoKB is still not functional through OpenCRAVAT. Is there an issue on their end?

**Comment by zhx828** [comment]
> @haochenz96 Yes, there is an issue. It is installed on run.opencravat.org, but there is no way to pass the OncoKB token to the jobs submitted to run.opencravat.org yet. Currently, the only way to run the OncoKB annotator is to run it locally - putting the token as the file `oncokb.txt` in the folder of `oncokb` annotator module. We can't do the same at run.opencravat.org since that would mean the same token will be used for all the users of run.opencravat.org - but then, are you guys at MSKCC Ok with that? If it is Ok, then I can install a token file in the server. Let me know.

Hi Rick, unfortunately, OncoKB token cannot be shared with others in anyway including academic usage. Please do no include a token for all users.

**Comment by rkimoakbioinformatics** [comment]
@zhx828 Sure, I thought so.
