### ISSUE TITLE
bug in "Original Input" annotator

### ISSUE THREAD

**Issue by EugeneEA** [KarchinLab/open-cravat#82]
Dear Rick, 
I think I found a bug in  "Original Input" currently in my hands it shows already "normalised" variants, here is an example after annotaion:
![1](https://user-images.githubusercontent.com/57629300/141455921-1c88fae2-0e4b-42d5-ae8e-e8213f1cdb29.png)
yet here is the original hg19 vcf file:
![image](https://user-images.githubusercontent.com/57629300/141456218-0bb063d6-8798-422b-a041-24150a56bc65.png)

I don't know is intentional behaviour or not, but it's a bit confusing (especially for someone who do not know what happens under the hood)

Best, Eugene

**Comment by rkimoakbioinformatics** [comment]
@EugeneEA Hi Eugene, can you try the latest vcf-converter (v2.1.1)? It now has "VCF Position", "VCF Ref Allele", and "VCF Alt Allele", which preserve the original data from VCF input files, as shown below.

![Screenshot from 2021-11-18 16-24-06](https://user-images.githubusercontent.com/13386712/142499250-02ee9f0e-3be7-4513-bd06-b5ea677415c8.png)

**Comment by EugeneEA** [comment]
Hi, interestingly enough in my run the annotator "Extra vcf INFO annotation" was not invoke. I assume because I used vcf with empty INFO filed (when I used normal vcf everything works as in your example):
![image](https://user-images.githubusercontent.com/57629300/142586256-6915606e-5c90-4d83-8b39-60140f1d0478.png)

The reason why I used such vcf is that I have a lot of samples which I eventually merge and, to keep file size reasonable, I delete all sample-level info ( I store such info separately in PLINK format and as a matter of fact as additional cravat annotator).

**Comment by rkimoakbioinformatics** [comment]
@EugeneEA Oh, I see. We'll update the vcf-converter so that the original chrom, pos, ref, and alt will be written regardless. I'll write here when it is published.

**Comment by rkimoakbioinformatics** [comment]
@EugeneEA vcf-converter 2.1.3 has just been published. Can you check if that version works for you? (showing VCF Position, VCF Ref, and VCF Alt allele even when INFO is empty)

**Comment by EugeneEA** [comment]
![image](https://user-images.githubusercontent.com/57629300/142869543-a93f609f-0be7-4298-82b1-f8ce46ba7c7e.png)
I'm currently running version 2.2.5

**Comment by rkimoakbioinformatics** [comment]
That is strange. Can you show me the result of `oc module info vcf-converter`? On my system vcf-converter 2.1.4 is available. Also, please let me know the value of `store_url` from `oc config system`.

**Comment by EugeneEA** [comment]
Here they are:
[vcf_conv_info.txt](https://github.com/KarchinLab/open-cravat/files/7581671/vcf_conv_info.txt)
store_url: https://store.opencravat.org

**Comment by rkimoakbioinformatics** [comment]
Thanks. vcf-converter 2.1.4 has been published to that store URL. Please check if it is available to you.

**Comment by EugeneEA** [comment]
nothing changes so far

**Comment by rkimoakbioinformatics** [comment]
I see. Actually, the newest vcf-converter versions require oc 2.2.6 or higher, I just recalled. If you update oc to 2.2.7 which is the latest version, the newest vcf-converter will appear as available. Please let me know.

**Comment by EugeneEA** [comment]
Hi, thanks, updating to 2.2.7 does fix the problem. Btw in the gui I was not notified that the update is available, with usuall red warning:
![image](https://user-images.githubusercontent.com/57629300/143189738-20790e34-200d-4349-af9b-09cb633dbffc.png)

**Comment by rkimoakbioinformatics** [comment]
@EugeneEA Yes, it was a designed change. There were some complaints about seeing the warning with every release. Thus, we decided to show that warning icon only when a major or a minor release is made. If a patch release is made (changing only the last digit), oc will not show the warning.
