### ISSUE TITLE
ncer annotator?

### ISSUE THREAD

**Issue by EugeneEA** [KarchinLab/open-cravat#87]
Hi, I'm digging into ncer annotator db (as an easy way to extract scores for some other analysis) and noticed, that there are few rows in the db where `beg int` > `end int` (here for example):
`sqlite> select * from chr1 where beg == 451677;`
`588|451677|451666|96.396289`

(CREATE TABLE chr1 (bin int, beg int, end int, score real); 
It does look a bit suspiciouse for me so may be there are some issues here 

Best, Eugene

**Comment by rkimkiromic** [comment]
@EugeneEA Thanks for letting us know. We'll investigate and get back to you.

**Comment by mstucky** [comment]
The issue with reversed beginning and ending locations has been resolved.  The database has been rebuilt with the latest data from Telentilab as well.  It is now published to the store.
