### ISSUE TITLE
TSV export problem

### ISSUE THREAD

**Issue by kokyriakidis** [KarchinLab/open-cravat#91]
Hi!

My 2 tsv export jobs `220127-231521 ` and `220127-231441` take forever to finish. Other tsv export jobs completed relatively fast. Is there any issue? The thing is that I cannot cancel and start again the tsv export by myself.

Thanks for your support!

KK

**Comment by rkimoakbioinformatics** [comment]
@kokyriakidis I removed blocking files and tsv report generation should be possible for the two jobs now. Please check. 

1) it is possible that the server runs out of memory while generating a report for a big job.
2) it would be nice if it is possible to cancel report generation.

We'll consider a patch for the two.
