### ISSUE TITLE
vcf converter seems to fail for some annotators

### ISSUE THREAD

**Issue by jkobject** [KarchinLab/open-cravat#93]
Running opencravat from latest version of:
the `karchinlab/opencravat` docker image

with parameters:
`oc run CDS-00rz9N.hg38-filtered.vcf.gz -l hg38 -t vcf --mp 2 --module-option vcfreporter.type=separate -d out -a spliceai alfa cscape dann dida encode_tfbs funseq2 genehancer gwas_catalog pharmgkb provean revel chasmplus civic mavedb uniprot loftool fitcons`

getting:
```
Input file(s): /cromwell_root/fc-secure-d2a2d895-a7af-4117-bdc7-652d7d268324/e12f3876-02fb-4981-9f81-886b08b67f9d/Mutect2/4109b0b5-81f9-4fc2-858c-09721652ac35/call-Filter/cacheCopy/CDS-00rz9N.hg38-filtered.vcf.gz
Genome assembly: hg38
Running converter...
Converter (converter) finished in 181.993s
Running gene mapper... finished in 173.492s
Traceback (most recent call last):
File "/usr/local/lib/python3.6/site-packages/cravat/cravat_class.py", line 548, in main
self.populate_secondary_annotators()
File "/usr/local/lib/python3.6/site-packages/cravat/cravat_class.py", line 1140, in populate_secondary_annotators
self._find_secondary_annotators(module, secondaries)
File "/usr/local/lib/python3.6/site-packages/cravat/cravat_class.py", line 1165, in _find_secondary_annotators
ret[sannot.name] = sannot
AttributeError: 'NoneType' object has no attribute 'name'
```

**Comment by jkobject** [comment]
using only "spliceai alfa cscape civic mavedb uniprot loftool fitcons". it works

**Comment by rkimoakbioinformatics** [comment]
@jkobject Can you check `oc module ls` and see if `hg19` module exists in your system? `encode_tfbs` runs and needs the output of `hg19` module and it seems that `hg19` module does not exist in your system.

**Comment by rkimoakbioinformatics** [comment]
The error message is a bit difficult for figuring out what is wrong. I'll improve it and let you know.
