### ISSUE TITLE
Converter error

### ISSUE THREAD

**Issue by spaul-genetics** [KarchinLab/open-cravat#94]
I am getting this error only for few variants. 

SOURCE:error.converter     
LINE:4580
INPUT:chr2         55181640            rs74621782        G             T              5015.21                PASS                AC=2;AF=0.008197;AN=244;AS_BaseQRankSum=.;AS_FS=0;AS_FilterStatus=PASS;AS_InbreedingCoeff=0.6897;AS_MQ=60;AS_MQRankSum=.;AS_QD=31.14;AS_ReadPosRankSum=.;AS_SOR=0.8;AS_VQSLOD=18.2956;AS_culprit=MQ;DB;DP=4218;ExcessHet=0.0089;FS=0;InbreedingCoeff=0.6897;MLEAC=2;MLEAF=0.008197;MQ=60;PG=0,20,46;POSITIVE_TRAIN_SITE;QD=29.74;SOR=0.8                GT:AD:DP:GQ:PGT:PID:PL:PP:PS 0/0:35,0:35:99:.:.:0,99,1485:0,119,1531:.                0/0:35,0:35:99:.:.:0,99,1323:0,119,1369:.              0/0:38,0:38:99:.:.:0,99,1485:0,119,1531:.                0/0:36,0:36:99:.:.:0,99,1355:0,119,1401:.              0/0:35,0:35:99:.:.:0,99,1358:0,119,1404:.                0/0:36,0:36:99:.:.:0,102,1530:0,122,1576:.            0/0:33,0:33:99:.:.:0,99,1326:0,119,1372:.                0/0:37,0:37:99:.:.:0,99,1360:0,119,1406:.              0/0:37,0:37:99:.:.:0,99,1485:0,119,1531:.                0/0:41,0:41:99:.:.:0,99,1422:0,119,1468:.              0/0:41,0:41:99:.:.:0,102,1530:0,122,1576:.                0/0:39,0:39:99:.:.:0,102,1530:0,122,1576:.            0/0:36,0:36:99:.:.:0,99,1485:0,119,1531:.                0/0:36,0:36:99:.:.:0,99,1458:0,119,1504:.              0/0:38,0:38:99:.:.:0,99,1485:0,119,1531:.                0/0:34,0:34:99:.:.:0,99,1485:0,119,1531:.              0/0:36,0:36:99:.:.:0,99,1390:0,119,1436:.                0/0:34,0:34:99:.:.:0,99,1450:0,119,1496:.              0/0:43,0:43:99:.:.:0,99,1485:0,119,1531:.                0/0:35,0:35:99:.:.:0,99,1407:0,119,1453:.              0/0:35,0:35:99:.:.:0,99,1485:0,119,1531:.                0/0:34,0:34:99:.:.:0,99,1485:0,119,1531:.              0/0:37,0:37:99:.:.:0,102,1530:0,122,1576:.                0/0:33,0:33:99:.:.:0,99,1326:0,119,1372:.              0/0:34,0:34:99:.:.:0,99,1485:0,119,1531:.                0/0:39,0:39:99:.:.:0,101,1530:0,121,1576:.            0/0:34,0:34:99:.:.:0,99,1485:0,119,1531:.                0/0:35,0:35:99:.:.:0,99,1406:0,119,1452:.              0/0:33,0:33:99:.:.:0,99,1193:0,119,1239:.                0/0:37,0:37:99:.:.:0,101,1473:0,121,1519:.            0/0:34,0:34:99:.:.:0,99,1485:0,119,1531:.                0/0:40,0:40:99:.:.:0,96,1440:0,116,1486:.              0/0:41,0:41:99:.:.:0,105,1575:0,125,1621:.                0/0:34,0:34:99:.:.:0,90,1350:0,110,1396:.              0/0:35,0:35:99:.:.:0,99,1270:0,119,1316:.                0/0:38,0:38:99:.:.:0,99,1485:0,119,1531:.              0/0:34,0:34:99:.:.:0,99,1057:0,119,1103:.                0/0:33,0:33:99:.:.:0,99,966:0,119,1012:. 0/0:33,0:33:99:.:.:0,99,973:0,119,1019:.                0/0:36,0:36:99:.:.:0,99,1485:0,119,1531:.              0/0:33,0:33:99:.:.:0,99,1059:0,119,1105:.                0/0:33,0:33:99:.:.:0,99,1007:0,119,1053:.              0/0:35,0:35:99:.:.:0,102,1116:0,122,1162:.                0/0:36,0:36:99:.:.:0,99,1063:0,119,1109:.              0/0:34,0:34:99:.:.:0,102,1059:0,122,1105:.                0/0:34,0:34:99:.:.:0,99,932:0,119,978:.   0/0:34,0:34:99:.:.:0,99,1485:0,119,1531:.                0/0:34,0:34:99:.:.:0,99,1187:0,119,1233:.              0/0:40,0:40:99:.:.:0,105,1555:0,125,1601:.                0/0:38,0:38:99:.:.:0,99,1485:0,119,1531:.              0/0:34,0:34:99:.:.:0,99,1485:0,119,1531:.                0/0:34,0:34:99:.:.:0,99,1228:0,119,1274:.              0/0:35,0:35:99:.:.:0,99,1485:0,119,1531:.                0/0:2,0:2:23:.:.:0,3,45:0,23,91:.  0/0:38,0:38:99:.:.:0,105,1575:0,125,1621:.                0/0:34,0:34:99:.:.:0,99,1256:0,119,1302:.              0/0:31,0:31:99:.:.:0,84,1260:0,104,1306:.                0/0:40,0:40:99:.:.:0,102,1530:0,122,1576:.            0/0:33,0:33:99:.:.:0,99,1226:0,119,1272:.                0/0:34,0:34:99:.:.:0,102,1183:0,122,1229:.            0/0:33,0:33:99:.:.:0,99,1111:0,119,1157:.                0/0:34,0:34:99:.:.:0,99,1200:0,119,1246:.              0/0:34,0:34:99:.:.:0,99,1485:0,119,1531:.                0/0:38,0:38:99:.:.:0,99,1369:0,119,1415:.              0/0:34,0:34:99:.:.:0,99,1323:0,119,1369:.                0/0:7,0:7:38:.:.:0,18,270:0,38,316:.          0/0:34,0:34:99:.:.:0,99,1485:0,119,1531:.                0/0:2,0:2:26:.:.:0,6,66:0,26,112:.               0/0:36,0:36:99:.:.:0,99,1302:0,119,1348:.                0/0:37,0:37:99:.:.:0,99,1485:0,119,1531:.              0/0:34,0:34:99:.:.:0,99,1485:0,119,1531:.                0/0:17,0:17:71:.:.:0,51,606:0,71,652:.      0/0:33,0:33:99:.:.:0,99,1195:0,119,1241:.                0/0:35,0:35:99:.:.:0,99,1225:0,119,1271:.              0/0:36,0:36:99:.:.:0,99,1485:0,119,1531:.                0/0:1,0:1:23:.:.:0,3,32:0,23,78:.  0/0:37,0:37:99:.:.:0,102,1530:0,122,1576:.                0/0:35,0:35:99:.:.:0,99,1485:0,119,1531:.              0/0:34,0:34:99:.:.:0,99,1197:0,119,1243:.                0/0:36,0:36:99:.:.:0,102,1530:0,122,1576:.            0/0:36,0:36:99:.:.:0,102,1530:0,122,1576:.                0/0:35,0:35:99:.:.:0,99,1307:0,119,1353:.              0/0:37,0:37:99:.:.:0,99,1289:0,119,1335:.                0/0:33,0:33:99:.:.:0,99,1094:0,119,1140:.              0/0:34,0:34:99:.:.:0,99,1158:0,119,1204:.                0/0:36,0:36:99:.:.:0,99,1259:0,119,1305:.              0/0:34,0:34:99:.:.:0,99,1485:0,119,1531:.                0/0:33,0:33:99:.:.:0,99,1254:0,119,1300:.              0/0:36,0:36:99:.:.:0,102,1243:0,122,1289:.                0/0:33,0:33:99:.:.:0,99,1078:0,119,1124:.              0/0:35,0:35:99:.:.:0,99,1485:0,119,1531:.                0/0:37,0:37:99:.:.:0,99,1485:0,119,1531:.              0/0:36,0:36:99:.:.:0,102,1530:0,122,1576:.                0/0:34,0:34:99:.:.:0,99,1230:0,119,1276:.              0/0:34,0:34:99:.:.:0,99,1320:0,119,1366:.                0/0:34,0:34:99:.:.:0,99,1333:0,119,1379:.                1|1:0,116:116:99:1|1:55181640_G_T:5057,349,0:5011,323,0:55181640                0/0:36,0:36:99:.:.:0,99,1485:0,119,1531:.              0/0:35,0:35:99:.:.:0,99,1341:0,119,1387:.                0/0:34,0:34:99:.:.:0,99,1131:0,119,1177:.              0/0:36,0:36:99:.:.:0,99,1485:0,119,1531:.                0/0:39,0:39:99:.:.:0,102,1530:0,122,1576:.            0/0:34,0:34:99:.:.:0,99,1134:0,119,1180:.                0/0:34,0:34:99:.:.:0,101,1136:0,121,1182:.            0/0:33,0:33:99:.:.:0,99,1037:0,119,1083:.                0/0:35,0:35:99:.:.:0,100,1481:0,120,1527:.            0/0:33,0:33:99:.:.:0,99,1139:0,119,1185:.                0/0:22,0:22:50:.:.:0,30,726:0,50,772:.      0/0:26,0:26:92:.:.:0,72,1080:0,92,1126:.                0/0:37,0:37:99:.:.:0,99,1485:0,119,1531:.              0/0:35,0:35:99:.:.:0,102,1530:0,122,1576:.                0/0:37,0:37:99:.:.:0,102,1517:0,122,1563:.            0/0:36,0:36:99:.:.:0,99,1124:0,119,1170:.                0/0:33,0:33:99:.:.:0,99,1051:0,119,1097:.              0/0:33,0:33:99:.:.:0,99,1103:0,119,1149:.                0/0:34,0:34:99:.:.:0,99,1485:0,119,1531:.              0/0:33,0:33:99:.:.:0,99,1138:0,119,1184:.                0/0:34,0:34:99:.:.:0,99,1114:0,119,1160:.              0/0:34,0:34:99:.:.:0,99,1243:0,119,1289:.                0/0:33,0:33:99:.:.:0,99,1065:0,119,1111:.              0/0:36,0:36:99:.:.:0,99,1485:0,119,1531:.                0/0:34,0:34:99:.:.:0,99,1485:0,119,1531:.
ERROR:must be real number, not NoneType

**Comment by rkimoakbioinformatics** [comment]
@spaul-genetics Can you post the traceback of the exception on the .log file here?

**Comment by spaul-genetics** [comment]
Here it is. I get this same error for a number of variants. 

[final_cravat.log](https://github.com/KarchinLab/open-cravat/files/8005536/final_cravat.log)

**Comment by rkimoakbioinformatics** [comment]
@spaul-genetics Thanks. It seems that there is no value for a field which is supposed to be a number. To pinpoint which field caused the issue, I need the header portion of your input file (the lines starting with `#`). Can I take a look at that part somehow?

**Comment by spaul-genetics** [comment]
Thanks @rkimoakbioinformatics . You are right some field on the INFO was missing. I removed unnecessary INFOs and it worked. Thanks for your help.

**Comment by rkimoakbioinformatics** [comment]
Great. Glad it was resolved.
