### ISSUE TITLE
Unable to install annotators

### ISSUE THREAD

**Issue by banerjeeshayantan** [KarchinLab/open-cravat#95]
I am using the open-cravat web app and after I open CHASMplus from the store, I am not able to figure out how to install this tool. There is no install option in the upper right-hand corner. Also, I don't see CHASMplus in the list of already installed annotators. What am I doing wrong?
![image](https://user-images.githubusercontent.com/7888886/153356823-0d19f85d-305a-4447-a84e-252337b8c853.png)

**Comment by rkimoakbioinformatics** [comment]
@banerjeeshayantan Sorry for the inconvenience. The server has been fixed and you'll see CHASMplus. Modules are supposed to be installed only by admin.

**Comment by banerjeeshayantan** [comment]
Great. I can access it now. Thanks for your prompt reply.
