### ISSUE TITLE
EXTRA VCF INFO Annotations are empty

### ISSUE THREAD

**Issue by kokyriakidis** [KarchinLab/open-cravat#96]
Hi! 

EXTRA VCF INFO Annotations for the jobs 220213-213934, 220213-213925 and 220213-213913 are empty. 

This a typical INFO field inside my vcf file:
```
TYPE=hyper;STRAND=-;MEDIATOR=ADAR;PD1-1_REFDEPTH=9;PD1-1_ALTDEPTH=1;PD1-1_FREQUENCY=0.1;PD1-1_COVERAGE=10;DJ=894;Homopolymer=0;Entropy=1.842;ED=19
```
It seems that it is vcf file specific. I used other vcf files and they work fine. I don't know why these vcf files cause this issue. 

Any guess?

Edit: I found the issue. Sample namings like PD1-1, PD1-2 caused the problem. Changing them to PD1_1 and PD1_2 solved the issue. So, be aware of this issue.

**Comment by rkimoakbioinformatics** [comment]
@kokyriakidis Hi, it seems that those jobs do not exist. Was the problem solved? If not, if an example file is available I can examine.

**Comment by kokyriakidis** [comment]
Oh sorry I deleted these jobs. Yes I solved the issue. OC had issues with sample names with dashes eg. "C1-1". Changing them to "C1_1" solved the issue. Maybe you can modify ox code to handle this kind of sample names. The problem appeared only in the EXTRA VCF INFO section. Everything else was showing up just fine.

**Comment by rkimoakbioinformatics** [comment]
@kokyriakidis Thanks. The server should handle "C1-1" without a problem by now (vcf-converter 2.1.4 fixes the problem). Please let me know if you still encounter the issue.

**Comment by kokyriakidis** [comment]
@rkimoakbioinformatics Names like "CGND-HRA-00450" do not work. The EXTRA VCF INFO section is empty.
